journal.bestiary.ally.title=盟國
journal.bestiary.bosses.title=地區首領
journal.bestiary.neutral.title=中立角色
journal.bestiary.plant.title=植物
journal.bestiary.quest.title=任務敵人和首領
journal.bestiary.rare.title=稀有敵人
journal.bestiary.regional.title=地區敵人
journal.bestiary.trap.title=陷阱
journal.bestiary.universal.title=普遍敵人
journal.catalog.armor.title=盔甲
journal.catalog.artifacts.title=文物
journal.catalog.bombs.title=炸彈
journal.catalog.brews_elixirs.title=釀造的酒和藥劑
journal.catalog.enchantments.title=魔法與詛咒
journal.catalog.exotic_potions.title=異域藥劑
journal.catalog.exotic_scrolls.title=異國風情捲軸
journal.catalog.food.title=食物
journal.catalog.glyphs.title=符號和詛咒
journal.catalog.melee_weapons.title=近戰武器
journal.catalog.misc_consumables.title=雜項消耗品
journal.catalog.misc_equipment.title=雜項設備
journal.catalog.potions.title=魔藥
journal.catalog.rings.title=戒指
journal.catalog.scrolls.title=捲軸
journal.catalog.seeds.title=種子
journal.catalog.spells.title=咒語
journal.catalog.stones.title=符文石
journal.catalog.thrown_weapons.title=投擲武器
journal.catalog.tipped_darts.title=帶尖飛鏢
journal.catalog.trinkets.title=小飾品
journal.catalog.wands.title=魔杖
journal.document.adventurers_guide.alchemy.body=如果你覺得消耗品沒用，可以把它當作煉金材料，或轉化成萬能煉金能量。給藥水和捲軸充能也能辨識它們！飾品是一種獨特的裝備，需要用煉金術製作和升級。它們需要魔法飾品催化劑和少量煉金能量才能製作。 （第一個煉金壺位於地牢的3層或4層。這些煉金壺附近也有煉金配方書頁。）
journal.document.adventurers_guide.alchemy.title=煉金術與飾品
journal.document.adventurers_guide.dieing.body=地下城探險危機四伏，大多數冒險者最終都會喪命。運氣固然重要，但最優秀的冒險者會運用各種技巧來提升勝算。 （如果你經常死亡也不要灰心，這款遊戲難度很高！專注於學習遊戲機制並穩步提升，而不是急於求成。）
journal.document.adventurers_guide.dieing.title=應對失敗
journal.document.adventurers_guide.examining.body=與其盲目衝鋒，不如先觀察敵人和周圍環境！養成仔細檢查所有新事物的習慣。 （你可以使用放大鏡按鈕進行檢查，然後選擇要檢查的內容。你也可以透過選擇圖示來查看增益或減益效果。）
journal.document.adventurers_guide.examining.title=檢查
journal.document.adventurers_guide.food.body=有效配給是提高生存幾率的最佳方法之一，你不一定要餓著肚子就吃！當你不餓的時候，你的生命值會緩慢恢復，所以如果你在滿血狀態下進食，恢復的生命值就會被浪費掉！如果你根據自己的生命值來控制進食節奏，你的食物就能保存更久。
journal.document.adventurers_guide.food.title=應對飢餓
journal.document.adventurers_guide.identifying.body=每個地下城中藥水和捲軸上的符號顏色都不同。未鑑定的裝備如果運氣好，可以升級或附魔，但也可能被詛咒！鑑定、升級或移除詛咒的捲軸對於降低使用未鑑定裝備的風險非常有用。 （你可以在日誌的目錄標籤頁中找到所有已鑑定物品的清單）
journal.document.adventurers_guide.identifying.title=識別物品
journal.document.adventurers_guide.intro.body=冒險者，你好！你正在閱讀《地下城精通之書》！這本指南最適合作為參考，它會神奇地告訴你何時閱讀每一頁最為合適。 （當日誌按鈕閃爍時，點擊它即可閱讀指南的內容！不過有些頁面缺失，或許你可以在地下城裡找到它們？）
journal.document.adventurers_guide.intro.title=介紹
journal.document.adventurers_guide.levelling.body=升級可以提升你的屬性並獎勵天賦點數，這在戰鬥中至關重要。最好確保你的角色在地下城的每一層都至少升一級。雖然快速通關、避免探索或戰鬥可能很誘人，但這樣做會讓你錯過補給和經驗。你可以在遊戲介面角落的狀態列查看英雄訊息，包括經驗值。點擊英雄頭像可以查看更多資訊。
journal.document.adventurers_guide.levelling.title=累積經驗
journal.document.adventurers_guide.looting.body=通常情況下，鎖著的房間或有障礙物的房間會有更好的戰利品。當障礙物擋住去路時，通常可以在同一層找到一件可以幫助你的物品。每個五層地牢區域你總能找到2瓶力量藥水和3張升級捲軸，因此它們是衡量你探索水平的絕佳指標。 （你可以在日誌視窗的備註標籤頁中查看地標和未使用的鑰匙清單。）
journal.document.adventurers_guide.looting.title=有效掠奪
journal.document.adventurers_guide.magic.body=魔法攻擊能輕易穿透盔甲，而且難以躲避。這意味著魔杖的傷害非常可靠，但也使得魔法敵人非常危險！然而，魔法攻擊總有其弊端。魔杖的使用次數有限，而且魔法敵人通常無法近距離施放魔法。面對會使用魔法的敵人時，學會如何阻止他們對你使用魔法至關重要。
journal.document.adventurers_guide.magic.title=魔法攻擊
journal.document.adventurers_guide.positioning.body=策略與裝備同等重要。良好的站位通常可以避免被包圍等不利局面。例如，大多數地牢都有狹窄的走廊，迫使敵人逐一與你交戰。這些走廊通常也設有入口，方便發動突襲！此外，還有許多巧妙的方法可以利用環境特徵，例如草地、水體、陷阱或坑洞。
journal.document.adventurers_guide.positioning.title=定位
journal.document.adventurers_guide.searching.body=地牢裡到處都是乍看難察覺的秘密之門和陷阱。如果你懷疑附近藏有門或陷阱，可以花點時間仔細搜尋。 （你可以按兩次放大鏡按鈕來搜尋周圍的所有方格。也許在你找到這個頁面的地方附近就藏著一些隱藏的門！）
journal.document.adventurers_guide.searching.title=搜尋
journal.document.adventurers_guide.strength.body=沒有時間去練習使用在地牢裡找到的武器和盔甲，所以你需要強大的力量才能有效地使用它們。力量藥水和升級捲軸是滿足高級裝備力量需求最有效的方法。最終使用高級裝備固然重要，但也不要忽略你現在就能使用的裝備。
journal.document.adventurers_guide.strength.title=力量
journal.document.adventurers_guide.surprise_attacks.body=突襲必定命中，因此對付蛇和幽靈等難以躲避的敵人尤其有效。你可以在敵人追擊你時，在他們進入門口後，或者在他們失去你的視線時，立即發動突襲。
journal.document.adventurers_guide.surprise_attacks.title=突襲
journal.document.adventurers_guide.title=地下城精通之書
journal.document.adventurers_guide.upgrades.body=越深入地下城，使用魔法升級的高級裝備就越重要，但你也需要足夠的實力才能正確使用它們。魔杖、戒指和神器不需要實力加成，但它們的用途有限，或在戰鬥中提供的幫助不如裝備直接。在地下城初期，合理選擇升級哪些裝備對於生存至關重要，也為後期成功奠定了基礎。
journal.document.adventurers_guide.upgrades.title=升級
journal.document.alchemy_guide.bombs.body=將普通的黑火藥炸彈與特定物質混合，即可製成威力更強的炸彈。
journal.document.alchemy_guide.bombs.title=增強型炸彈
journal.document.alchemy_guide.brews_elixirs.body=藥劑和靈藥是具有多種效果的高級藥水，通常只能使用一次。
journal.document.alchemy_guide.brews_elixirs.title=釀造的酒和藥劑
journal.document.alchemy_guide.energy_food.body=許多配方需要水晶煉金能量，這種能量可以透過在煉金術鍋中分解消耗品來獲得。給藥水或捲軸充能也能辨識這些配方。有些需要能量的配方是魔法配方，但這些配方類似於傳統烹飪。
journal.document.alchemy_guide.energy_food.title=能源與食物
journal.document.alchemy_guide.exotic_potions.body=藥劑可以與能量混合，製成奇異的藥劑。它們效果更強勁，但用途往往有所不同。
journal.document.alchemy_guide.exotic_potions.title=異域藥劑
journal.document.alchemy_guide.exotic_scrolls.body=異域捲軸需要消耗一些能量和一個捲軸才能製作。它們比異域藥劑效果更強，價格也更貴。
journal.document.alchemy_guide.exotic_scrolls.title=異國風情捲軸
journal.document.alchemy_guide.potions.body=歡迎來到《煉金術的實用應用》！本書是一本煉金術配方參考書，教你如何在煉金術鍋中製作物品。我們將從最具代表性的配方開始：藥水！使用三顆種子即可隨機煉製一瓶藥水！每顆種子都對應一種藥水，使用多顆相同的種子可以提高煉製與種子相關的藥水的機率。
journal.document.alchemy_guide.potions.title=簡介和魔藥
journal.document.alchemy_guide.spells.body=魔法被封存在水晶中，可以提供多種效果，通常可以多次使用。
journal.document.alchemy_guide.spells.title=咒語
journal.document.alchemy_guide.stones.body=將捲軸放入煉金鍋中，捲軸的魔法就會注入鍋內的兩塊石頭中。這樣就能生成符文石，並辨識出捲軸的種類！
journal.document.alchemy_guide.stones.title=製作符文石
journal.document.alchemy_guide.title=煉金術指南
journal.document.alchemy_guide.weapons.body=一些較輕或更具魔法的武器可以用於煉金術！每套投擲武器都能產生足夠的液態金屬，完全修復另一套同等級同階的武器。請注意，煉金術會摧毀整套武器，即使其中一部分並不完整！一根魔杖能產生足夠的奧術樹脂，升級兩根同等級的魔杖，但最高只能升級到+3。
journal.document.alchemy_guide.weapons.title=強化武器
journal.document.caves_explorer.alive.body=夏至23日，308年。其中一台矮人機器不知怎麼的活了過來！我們只是路過，它就衝了過來，用它巨大的金屬拳頭差點把我們隊伍裡的兩個人捏碎。幸好我隨身帶著我的分解魔杖。幾發精準的分解光束就把這隻怪物化成了廢鐵。讓我困惑的是，我們根本沒有招惹這台機器。矮人不可能把機器設計得如此好鬥，它簡直就像是在伏擊我們！至少我這次還能幫上同伴的忙。 ——阿奇博爾德
journal.document.caves_explorer.alive.title=它活了！
journal.document.caves_explorer.city.body=夏至21日，308年。現在已經過去三週了，在過去十天裡，我們一直在不斷深入探索，終於到達了礦井底部。我們發現了各種金屬裝置和一道巨大的大門，它阻擋了通往古老矮人都市的入口。鐵匠警告我們一些機械裝置。它們顯然是用於區域防禦的，一旦受到干擾就會啟動。我們在城裡沒有其他目的，而且這些金屬的廢料價值微乎其微，所以我們覺得最好聽從他的警告，回到城外。我必須承認我很好奇，但下去探險絕對不值得冒險。 ——阿奇博爾德
journal.document.caves_explorer.city.title=城市入口
journal.document.caves_explorer.discover_hint=你可以在特定區域找到這段文字，但前提是必須先找到該集合中的所有先前文字。
journal.document.caves_explorer.expedition.body=西元308年夏至日，今天我們為期四週的廢棄矮人礦坑探險正式開始！我受國王親自委派，前來探索這區域。我的主要目標是尋找尚未開發的自然資源，並勘測洞穴，以尋找潛在的監獄建設計畫。雖然我有能力自衛，但遵照國王的意願，我接受了城衛隊的護送。他們是一群笨蛋，但只要他們不拖慢我的速度，他們的存在就還可以忍受。我們預計在傍晚前清理完下水道並抵達礦井。 ——阿奇博爾德‧德拉蒙德，南方巫師學院大法師。
journal.document.caves_explorer.expedition.title=探險開始！
journal.document.caves_explorer.gold.body=夏至四日，308年。我們這幾天收穫豐富！建立好營地後，我們便開始探索廢棄礦井的上層區域。雖然矮人留下了不少無用的雜物，但許多洞壁上也堆滿了黃金！可惜的是，我們並非第一批來到這裡的人。洞穴裡到處都是兇猛的野生動物，而且似乎成群的豺狼人也對黃金很感興趣。我承認我對我的護衛有些苛刻，他們比我預想的要能幹得多，既是優秀的探險家，又是出色的保鑣。即便如此，我們仍然有許多礦井需要探索。 ——阿奇博爾德
journal.document.caves_explorer.gold.title=好多黃金！
journal.document.caves_explorer.report.body=308年夏28日，今天我們將收拾好行李，準備離開。恰逢其時，我們小組裡有好幾個人自從上次遭遇那台兇猛機器後就開始做惡夢。這或許只是疲勞所致，但他們的惡夢卻驚人地相似。總而言之，礦井上部區域相當安全。如果能找到黑金的用途，開採它可能會非常有利可圖。開闊的礦區也非常適合城市的建設規劃。然而，下部礦井則更加危險，應避免前往。接下來幾天，我會把這些都寫進我的最終報告裡。 ——阿奇博爾德
journal.document.caves_explorer.report.title=最終報告
journal.document.caves_explorer.title=探險家日誌
journal.document.caves_explorer.troll.body=夏至11日，308年。在我們開始探索礦井中部之後，我們遇到了一張友善的臉！嗯……算是友善吧。一個洞穴巨魔在那裡蓋了個小鐵匠鋪。他脾氣暴躁，不太愛說話，但還是幫我們修好了裝備，換取了一些金子。可惜的是，這位巨魔鐵匠也告訴我們，這些漂亮的金子並不像看起來那麼好。他稱之為“黑金”，而且顯然會在陽光下迅速褪色。這倒也解釋了為什麼這裡從來沒有因為資源而發生衝突。我想我們需要再深入挖掘一下，看看有沒有更值錢的東西。 ——阿奇博爾德
journal.document.caves_explorer.troll.title=遇到一個巨魔
journal.document.city_warlock.discover_hint=你可以在特定區域找到這段文字，但前提是必須先找到該集合中的所有先前文字。
journal.document.city_warlock.failure.body=看來我也是個傻瓜。我以為新王需要朝廷心甘情願地臣服於他，但現在看來，他甚至有能力控制那些反抗他的人。我盲目地把所有最強大的反對者都帶到了他的面前，讓他親自把他們變成奴隸。現在，他那股死靈能量的浪潮席捲全城，瞬間將大多數人變成了他的信徒。少數仍保有自由意志的人正在逃離。我選擇留下來，盡我所能地觀察，尋找機會。憑藉我擁有的魔法力量，我應該可以安全地躲藏一段時間。
journal.document.city_warlock.failure.title=失敗
journal.document.city_warlock.more_powerful.body=時間流逝變得難以把握，但距離我上次記錄已經過去大約一周了。我們的文明徹底崩潰了。城門緊閉，社會運作停止，空蕩蕩的矮人軀殼在走廊上遊蕩。然而，新王的力量卻與日俱增。他的意志力與日俱增，但同時也在改變。我無法描述，但感覺他似乎已經不再是矮人了。我開始接受，我所能做的或許只有記錄這些事件。我會盡可能地留在這裡，直到我的意志開始衰弱，然後撤退。
journal.document.city_warlock.more_powerful.title=更強大
journal.document.city_warlock.new_power.body=這裡究竟發生了什麼事？新王散發出的力量確實與之前不同，但似乎還有其他因素。這股新的力量似乎源自於我們城市最深處的殿堂。更令人費解的是，上層都市的活動也減少了。我不知道下面發生了什麼，但它幾乎吸引了新王所有的注意力。重返深層殿堂固然危險，但我必須找出造成這種改變的原因。或許新王終究也有弱點？
journal.document.city_warlock.new_power.title=新的力量
journal.document.city_warlock.old_king.body=今天是魔法時代33年2月5日。如果地上世界居民讀到這段文字，現在應該是264年冬天。我的名字是泰莫·扎希爾，據我所知，我是矮人宮廷中最後一位倖存者。我們的國王駕崩了，取而代之的是我的一位昔日同僚，他已被權力沖昏了頭。宮廷中的其他人如同傻瓜一般臣服於他，並在過程中失去了自由意志。只有我預見了這一切，並在他的儀式完成之前逃走了。核心圈已經覆滅，但新國王的力量尚未完全滲透到所有人。我必須盡快組織起抵抗。我絕不允許我們光榮的文明落入這個狂妄自大的傢伙之手！
journal.document.city_warlock.old_king.title=國王駕崩
journal.document.city_warlock.resistance.body=消息似乎傳播得很快。僅僅幾天時間，我就已經集結了一支效忠老國王的小部隊。他們當中精通魔法的人不多，但幾乎整個武僧團都已加入我們。我們應該足以對付一個瘋狂的矮人和他那群奴隸。同時，新國王藏身於我們城市的內殿。毫無疑問，他已經耗盡了大部分力量，希望在遇到更多抵抗之前恢復元氣。我們將在幾個小時後發動攻擊。如果運氣好的話，我們能夠在今晚結束前組成一個臨時議會，並使我們這個奇妙的城市恢復穩定。
journal.document.city_warlock.resistance.title=抵抗
journal.document.city_warlock.seen_it.body=我已目睹下方的一切，卻無法言喻。我雙手顫抖不已，努力將思緒訴諸筆端。這究竟是何緣故？是新王所為嗎？這毫無道理。或許是他肆意濫用權力招致了這一切？我曾經希望拯救我們的文明，如今卻發現整個世界都岌岌可危。不知為何，國王似乎是兩害取其輕。我別無選擇，為了大局，我願獻出生命。請指引我，我的王，請將我化作工具，阻止尤格-澤瓦的入侵！
journal.document.city_warlock.seen_it.title=我看過了
journal.document.city_warlock.title=術士日誌
journal.document.halls_king.amulet.body=我成功了！我不知道會發現什麼，但我在那裡發現的東西遠遠超出了我的想像。如此強大的力量，就擺在那裡等著我去獲取，而這一切都屬於我！有了它，朝廷裡的那些蠢貨就不敢再跟我作對了。想到各種羞辱他們的方法，我就興奮不已。見鬼，何必止步於此，如果我願意，我有足夠的力量把他們全部毀滅！這或許有點過頭了，但我不能猶豫太久，否則他們會起疑心的。我想我應該把這股強大的力量稱為延多護符！
journal.document.halls_king.amulet.title=護身符
journal.document.halls_king.attrition.body=我自有應對之策。它的力量無窮無盡，但它侵占這個世界的能力卻並非如此。它依靠爪牙和化身為其效力，同時積蓄力量，企圖奪取護身符。雖然我並未實際擁有護身符，但我依然完全掌控著它的力量。整個矮人城都任我調遣，我在人數上也佔優勢。我只需不斷派遣士兵阻止它奪取護身符，便能透過消耗戰逐步贏得這場戰爭！我，羅德尼，矮人之王，必將戰勝你，尤格-澤瓦！
journal.document.halls_king.attrition.title=損耗
journal.document.halls_king.discover_hint=你可以在特定區域找到這段文字，但前提是必須先找到該集合中的所有先前文字。
journal.document.halls_king.new_king.body=我是國王，哈哈哈哈哈哈！他們竟然讓我這麼做了！幾乎沒費什麼力氣，他們就同意讓我透過一場盛大的儀式與他們「分享」這份力量。瞬間，他們就從一群嘲笑者變成了我沉默的臣民！不出所料，泰莫一遇到麻煩就像個懦夫一樣逃跑了。我已經能感覺到他正在組建的反抗力量。我想我會讓他繼續下去，這樣他就能把所有同謀都送到我家門口！顯然，王國也不尊重我，我想我也會解決這個問題。矮人王
journal.document.halls_king.new_king.title=新王
journal.document.halls_king.rejection.body=蠢貨！過去33年裡，我們的王國以新的魔法科技蓬勃發展。我們學會如何召喚元素精靈並駕馭它們，但不知為何，現在進一步的實驗卻「太危險」了。我知道真相。我的理論被否定與理論本身無關，而完全是因為提出這些理論的人。他們可能都在背後嘲笑我。夠了！我不在乎他們說什麼，我要獨自探索宇宙的盡頭，並將我的發現全部據為己有！ ——R.
journal.document.halls_king.rejection.title=拒絕
journal.document.halls_king.ritual.body=今天早些時候，泰莫爾當眾質問我，非要我解釋我新獲得的力量來源。我盡力敷衍了他，但我能感覺到宮廷裡其他人的目光再次投向了我。我原本希望暴風雨前的寧靜能讓我多享受一會兒，但現在看來已經無關緊要了。我已經決定要做什麼了。我會聲稱我的力量來自一種新的儀式，並提出要為其他術士和國王施展這個儀式。儀式結束後，我將成為國王！泰莫爾當然會抗議，但面對如此強大的力量，我懷疑他們不會聽他的話！所有人都將臣服於我！ ——未來的矮人之王
journal.document.halls_king.ritual.title=儀式
journal.document.halls_king.thing.body=出問題了。提莫爾被輕易地解決了，但我在外層位面的搜尋似乎並沒有逃過它的眼睛。某種……「東西」……被吸引到我的世界，正從下層大廳的底部強行闖入。更糟的是，那裡正是我存放護身符的地方！真是個惡毒的傢伙，明明還有很多力量等著我去奪取，它為什麼非要剝奪我的力量呢？儘管我擁有強大的力量，但我不能貿然衝上去和它戰鬥。它真正的力量深不可測，但我一定有辦法限制它。我一定要捍衛我的寶物！
journal.document.halls_king.thing.title=怪形
journal.document.halls_king.title=???的日記
journal.document.intros.caves.body=這些人口稀少的洞穴延伸至廢棄監獄下方。它們礦產資源豐富，曾是下方矮人社會繁榮的貿易和工業中心，但隨著矮人沉迷於黑暗魔法，這些洞穴最終被廢棄。如今，洞穴裡大多棲息著地下野生動物、豺狼人和廢棄的機械；很可能受到了與影響地上區域的同一股力量的侵蝕。
journal.document.intros.caves.title=洞穴
journal.document.intros.city.body=矮人大都會曾是所有矮人城邦中最偉大的。在其鼎盛時期，矮人們建造了精妙絕倫的金屬與魔法機器，使他們的城市得以迅速擴張。然而，有一天，城門突然關閉，矮人從此消失。少數在城門關閉時逃出的人講述了一個瘋狂術士篡奪王位的故事，以及他所掌握的可怕魔法。
journal.document.intros.city.title=矮人大都會
journal.document.intros.discover_hint=首次進入特定區域時，您可以看到這段文字。
journal.document.intros.dungeon.body=在你之前，許多英雄都曾從地上城市冒險進入地下城，但大多數人從此杳無音信。據說，一股古老的邪惡力量潛伏在地下城深處，守護著威力無比的延多護符。即使現在，黑暗能量依然從地下城深處湧出，向上蔓延至城市之中。你是否能夠征服地下城，奪取護符？是時候開啟你的冒險之旅了！
journal.document.intros.dungeon.title=地城
journal.document.intros.halls.body=矮人都城深處的這些大廳已被黑暗魔法扭曲。過去，這裡曾是矮人王麾下精英術士的宮廷所在地，但如今，它們似乎已被某種更加邪惡的力量所佔據……各種恐怖的惡魔生物棲息於此，受制於某種可怕的黑暗力量。如果矮人王並非這股蔓延的腐化之源，那麼，這地下的某種東西必定是罪魁禍首。務必小心行事，鮮有冒險家曾經深入此地…
journal.document.intros.halls.discover_hint=你可以在特定區域找到這段文字，但前提是必須先找到該集合中的所有先前文字。
journal.document.intros.halls.title=惡魔大廳
journal.document.intros.prison.body=多年前，這裡建了一座監獄，用來關押危險的罪犯。監獄管理嚴密，戒備森嚴，來自全國各地的罪犯都被押送到這裡服刑。但不久之後，一股黑暗的瘴氣從監獄下方蔓延開來，扭曲著獄警和囚犯的心智。為了應對日益嚴重的混亂，城裡封鎖了整個監獄。沒有人知道那些被遺棄在這座高牆之內的人最終的下落…
journal.document.intros.prison.title=監獄
journal.document.intros.sewers.body=地牢的上層其實是城市的下水道系統。隨著黑暗能量從下方湧上來，原本無害的下水道生物變得越來越兇猛。城市不得不派遣守衛巡邏隊到這裡，以維護上方居民的安全。這裡很危險，但至少這裡邪惡的魔法力量較弱。
journal.document.intros.sewers.title=下水道
journal.document.intros.title=區域介紹
journal.document.prison_warden.discover_hint=你可以在特定區域找到這段文字，但前提是必須先找到該集合中的所有先前文字。
journal.document.prison_warden.journal.body=西元362年春季1日，這是監獄長基亞娜‧史密斯工作日誌的第一篇。最近發生了很多事，所以我決定開始寫日記，整理一下我的思緒。管理一座位於地下半英里的監獄從來都不是一件容易的事，但最近似乎發生了一些有組織的騷亂。囚犯們無緣無故地鬧事，而且拒絕解釋原因。一些獄警開始說這裡鬧鬼。我不能讓我的手下散播謠言，但我也不能完全怪他們的不安。 ——史密斯
journal.document.prison_warden.journal.title=寫日記
journal.document.prison_warden.letter.body=湯瑪斯，你一直是個好朋友，所以我幫你個忙。今晚你值班的時候，把天狗的牢房鎖好加固，把鑰匙丟進某個壁龕裡，然後出去。其他囚犯是否無人看管都無所謂，很快這裡就沒人能離開了。不過那個怪胎必須被關好，要是他跑了，誰也說不準他會幹出什麼事。別把這件事告訴任何人，也別來找我。船長必須與船同沉。 ——琪亞娜
journal.document.prison_warden.letter.title=致托馬斯的信
journal.document.prison_warden.mines.body=363年冬至54日，今天城裡來了一群工程師，說是來封鎖通往下方礦坑的舊入口。我猜城裡是不想再維護這條通道了。像往常一樣，我事先毫不知情。他們的首席工程師還跟我胡扯了些什麼矮人魔法從礦坑洩漏出來之類的鬼話。我一個字都不信。新來的工作人員讓情況好多了，但問題的根源依然沒有解決。一定有什麼事影響到了這裡的囚犯，拆掉幾面牆是解決不了問題的。 ——史密斯
journal.document.prison_warden.mines.title=封鎖地雷
journal.document.prison_warden.no_support.body=364年春季11日，\n\n，這座城市到底在想什麼？我緊急請求援助後，杳無音信，連個像往常被拒絕後那樣空洞的道歉都沒有。 \n\n，同時，囚犯的情況持續惡化，甚至有些獄警也開始惹事生非。他們打算就這麼放任事態發展，直到爆發暴亂嗎？ ！ \n\n，至少湯瑪斯一如既往地可靠。他的組織工作至關重要，他提出的啟用那些老舊的DM-100裝置的想法雖然令人遺憾，但卻是必要的。我相信我能重新掌控局面，我只是需要一些該死的支持！ \n——史密斯
journal.document.prison_warden.no_support.title=不支援
journal.document.prison_warden.recruits.body=362\n\n春季80日，正如承諾的那樣，今天來了一批新兵。看起來和往常一樣，有幾個有前途的，還有很多只想拿薪水的嘍囉。不過，有了這些新兵，應該能對我們最近那些不守規矩的囚犯大有幫助。 \n\n在這樣的工作中，知道誰值得信任至關重要。新來的托馬斯看起來特別有前途。我現在需要盡可能多的幫助，所以如果他表現出色，我會盡快提拔他。 \n——史密斯
journal.document.prison_warden.recruits.title=新兵
journal.document.prison_warden.rotberry.body=363年秋季23日，今天收到菲利克斯送的一份很棒的禮物。那是一種鮮紅色的灌木，叫做「腐莓」。我之前跟他說過這個地方有多陰森，看來他聽到了。他說這種植物其實不喜歡光照和水，所以我只需要每個月修剪一次葉子就行了。不過修剪肯定很重要，他在信裡提了十幾次。當然，菲利克斯從來不會白白幫忙。他說這種植物結的種子很適合當魔杖，所以每次它結出種子的時候，我自然要給他一些。 ——史密斯
journal.document.prison_warden.rotberry.title=腐爛漿果
journal.document.prison_warden.title=典獄長日誌
journal.document.sewers_guard.crabs.body=376年冬至11日，親愛的爸爸媽媽：老鼠已經夠煩人了，更深處居然還有巨蟹！其中一隻從我身邊衝過去，把李咬得夠嗆，幸好我們把它幹掉了。湯瑪斯說這不是我的錯，但我知道他只是想安慰我。謝天謝地，我們出去的時候遇到了一位冒險者，他有一些多餘的太陽草藥膏。沒有那東西，李可能就活不下去了。我看到那位冒險者離開前盯著一朵玫瑰看，他們說那是別人送的。如果有人這麼關心他們，為什麼還要冒著生命危險來到這裡？這不正是我現在做的嗎？我覺得自己力不從心。
journal.document.sewers_guard.crabs.title=巨型螃蟹！
journal.document.sewers_guard.dangerous.body=375年秋天第88天，親愛的爸爸媽媽：我現在終於明白為什麼薪水這麼高了，下水道裡到處都是怪物！那些「害蟲」和「不法之徒」都是嗜血的巨鼠和成群的憤怒豺狼人。幸好我的隊友們都很專業。我們的隊長湯瑪斯是這方面的專家。我正在努力學習，以免成為大家的負擔。這份工作比我想像的危險得多。我很高興現在不能把這些寄出去，不想讓你們擔心。我會注意安全的。 ——索妮亞
journal.document.sewers_guard.dangerous.title=危險的處境…
journal.document.sewers_guard.discover_hint=你可以在特定區域找到這段文字，但前提是必須先找到該集合中的所有先前文字。
journal.document.sewers_guard.guild.body=376年冬至23日，親愛的爸爸媽媽：這次沒有遇到新的怪物，我們巡邏時卻碰上了盜賊公會的一小隊人。我聽說這個公會的一切都很糟糕，但我的隊友似乎和他們很友善。湯瑪斯和其中一個盜賊交換了情報和補給，然後我們就分道揚鑣了。我不明白，我們不是應該消滅這些不法之徒嗎？湯瑪斯甚至叮嚀過不要把這件事告訴任何指揮官。不過，他們的情報和補給非常有用，我們實在不想再打仗了。看來我們只能一起面對這一切了。
journal.document.sewers_guard.guild.title=盜賊公會
journal.document.sewers_guard.lost.body=376年冬至40日，我和湯瑪斯迷路了。我們和豺狼人戰鬥時與隊伍其他成員走散了。我們倆都沒受傷，但下水道就像迷宮。湯瑪斯說他知道一條出路，但要從下水道底部的舊監獄入口開始。我真不想再往下走了，但我們沒有口糧，而且下去比到處找巡邏路線快得多。沒事的，湯瑪斯知道該怎麼做。
journal.document.sewers_guard.lost.title=我們迷路了
journal.document.sewers_guard.new_position.body=375年秋天第85天，親愛的爸爸媽媽：我早就告訴過你們，在城衛隊辛苦工作會有回報的。我升職啦！我被邀請加入一個專門清理下水道的專家小組。據說那裡鼠患成災，還有不法之徒出沒，我們的任務就是把它們清除掉。工作很髒，但是下水道冬天很暖和，而且薪水是普通衛兵的三倍！不過，這件事有點保密，所以我不能真的把這封信寄出去。不寫信給你們感覺很奇怪，所以我還是會繼續寫信給你們的。也許有一天我可以把它們給你看。 \n\n祝好，\n- Sonya
journal.document.sewers_guard.new_position.title=我的新職位！
journal.document.sewers_guard.not_worth.body=我和托馬斯在監獄入口遇到了一種巨大的黏液怪物。還沒等我們反應過來，它就用魔法攻擊了我們。湯瑪斯承受了大部分傷害。他已經死了。再多的錢也彌補不了這一切。我要走湯瑪斯告訴我的那條路離開。然後我會用我當守衛賺的錢帶著我的父母離開這座被詛咒的城市。我的一部分希望國王對這一切有所安排，但我對此表示懷疑。我留下這些信是為了警告其他人。這裡不隻巨鼠和螃蟹，肯定有什麼非常不妙的事情發生。
journal.document.sewers_guard.not_worth.title=不值得
journal.document.sewers_guard.title=守衛的信件
journal.notes$landmark.alchemy=煉金壺
journal.notes$landmark.demon_spawner=惡魔生成器
journal.notes$landmark.distant_well=遠處的井
journal.notes$landmark.garden=花園
journal.notes$landmark.ghost=悲傷的鬼魂
journal.notes$landmark.imp=雄心勃勃的小鬼
journal.notes$landmark.rat_king=鼠王
journal.notes$landmark.sacrificial_fire=祭祀之火
journal.notes$landmark.shop=店鋪
journal.notes$landmark.statue=動畫雕像
journal.notes$landmark.troll=巨魔鐵匠
journal.notes$landmark.wandmaker=老魔杖匠
journal.notes$landmark.well_of_awareness=意識之井
journal.notes$landmark.well_of_health=身體健康
