levels.cavesbosslevel.energy_desc=這裡的地面冒著火花，踩上去很危險。火花似乎朝著某個方向聚集……也許它們通往電源？
levels.cavesbosslevel.gate_desc=一道巨大的金屬大門擋住了通往矮人都城的道路。大門中央的金屬箱發出嗡嗡的響聲，它一定與附近的電路和機器相連。或許摧毀DM-300就能打開這道大門？
levels.cavesbosslevel.gate_desc_broken=這扇門肯定與DM-300有某種聯繫，因為DM-300被擊敗時它就爆炸了。現在只剩下碎片了。
levels.cavesbosslevel.gate_name=金屬門
levels.cavesbosslevel.water_desc=這裡電力供應充足，水可能並不總是安全的…
levels.cavesbosslevel.wires_desc=這裡地面部分被挖開，露出一些粗大的裸露電線。它們應該是連接各種馬達的。這些電線裡面一定有電流通過。如果DM-300走到這裡，它或許能從中汲取電力。
levels.cavesbosslevel.wires_name=裸露的電線
levels.caveslevel.bookshelf_desc=誰會在山洞裡放書架？
levels.caveslevel.entrance_desc=梯子通往上層深處。
levels.caveslevel.exit_desc=梯子通往更深的地下。
levels.caveslevel.grass_name=螢光苔蘚
levels.caveslevel.high_grass_desc=巨大的蘑菇擋住了視線。
levels.caveslevel.high_grass_name=螢光蘑菇
levels.caveslevel.region_deco_desc=一座大型全金屬建築，很可能是矮人們以前在這裡採礦時建造的。你似乎可以看到頂部有廢棄已久的礦車軌道。
levels.caveslevel.region_deco_name=金屬結構
levels.caveslevel.wall_deco_desc=牆上可以看到一條礦脈。是金子嗎？
levels.caveslevel.water_name=冰冷的水
levels.citybosslevel.summoning_desc=這個基座中央有一個巨大的開口，幾乎散發著黑暗能量。矮人王利用這些基座作為他亡靈魔法的焦點，並能召喚僕從。僕從出現前，基座需要充能幾個回合，而召喚的僕從類型則透過累積的魔法能量來預示。
levels.citybosslevel.summoning_name=召喚基座
levels.citybosslevel.throne_desc=這座氣勢恢宏的王座是矮人帝國的王座，如今已被一位權力欲極強的死靈法師佔據。王座似乎包含一些魔法或機械部件，矮人國王坐在上面時可能會獲得額外的力量。
levels.citybosslevel.throne_name=王座
levels.citylevel.bookshelf_desc=書架上擺滿了不同學科的書籍。
levels.citylevel.deco_desc=這裡缺了幾塊磁磚。
levels.citylevel.entrance_desc=一條斜坡通往更深的水域。
levels.citylevel.exit_desc=一條斜坡通往更深的水域。
levels.citylevel.high_grass_name=高大盛開的花朵
levels.citylevel.region_deco_desc=一個高高的基座，頂端燃燒著明亮的綠色魔法火焰。火焰非常濃密，幾乎像固體一樣。
levels.citylevel.region_deco_name=燃燒的基座
levels.citylevel.sp_desc=地板上鋪著厚厚的地毯。
levels.citylevel.statue_desc=這座雕像描繪的是一位矮人擺出英勇的姿勢。
levels.citylevel.upcoming_quest_intro_no=留在這裡
levels.citylevel.upcoming_quest_intro_title=開發者留言
levels.citylevel.upcoming_quest_intro_yes=進入金庫
levels.citylevel.water_name=顏色可疑的水
levels.features.chasm.chasm=深淵
levels.features.chasm.jump=你真的想跳進深淵嗎？從那麼高的地方摔下去會很痛的。
levels.features.chasm.no=不，我改變主意了。
levels.features.chasm.ondeath=你墜亡了…
levels.features.chasm.rankings_desc=撞擊中身亡
levels.features.chasm.yes=是的，我知道自己在做什麼。
levels.hallslevel.bookshelf_desc=書架上，用古代語言寫成的書微微冒著熱氣。
levels.hallslevel.grass_name=餘燼苔蘚
levels.hallslevel.high_grass_name=餘燼菌
levels.hallslevel.region_deco_desc=一塊巨大的石頭，似乎是從天花板或附近的牆壁上脫落下來的。
levels.hallslevel.region_deco_name=一塊碎石
levels.hallslevel.statue_desc=這根柱子是用真正的人類頭骨製成的。太棒了。
levels.hallslevel.statue_name=支柱
levels.hallslevel.water_desc=它看起來像熔岩，但很冷，觸摸起來可能很安全。
levels.hallslevel.water_name=冷熔岩
levels.level$feeling.chasm_desc=你的腳步聲在地牢中迴盪。
levels.level$feeling.chasm_title=深淵地板
levels.level$feeling.dark_desc=你能聽到敵人在黑暗中移動的聲音。
levels.level$feeling.dark_title=深色地板
levels.level$feeling.grass_desc=空氣中瀰漫著濃鬱的植物香氣。
levels.level$feeling.grass_title=草地
levels.level$feeling.large_desc=這個地牢樓層看起來異常大。
levels.level$feeling.large_title=大地板
levels.level$feeling.secrets_desc=這裡的氣氛暗示著這一層隱藏著許多秘密。
levels.level$feeling.secrets_title=秘密樓層
levels.level$feeling.traps_desc=這裡的地面似乎特別濕滑。
levels.level$feeling.traps_title=陷阱地板
levels.level$feeling.water_desc=你聽到周圍有水花飛濺的聲音。
levels.level$feeling.water_title=水底
levels.level.alchemy_desc=這個罐子裡裝滿了魔法水。你可以把各種物品放進罐子裡，創造出新的東西！
levels.level.alchemy_name=煉金壺
levels.level.barricade_desc=木製路障雖然牢固，但多年使用已乾裂。它會著火嗎？
levels.level.barricade_name=路障
levels.level.bookshelf_name=書架
levels.level.chasm_desc=你看不到底部。
levels.level.chasm_name=深淵
levels.level.closed_door_name=關上的門
levels.level.crystal_door_desc=這扇上鎖的門是由魔法水晶製成的。你可以透過水晶看到裡面，但你需要一把水晶鑰匙才能打開它。
levels.level.crystal_door_name=水晶門
levels.level.default_name=？ ？ ？
levels.level.embers_desc=地面上滿是餘燼。
levels.level.embers_name=餘燼
levels.level.empty_well_desc=井水乾涸了。
levels.level.empty_well_name=空井
levels.level.entrace_name=深度入口
levels.level.entrance_desc=樓梯通往上層。
levels.level.exit_desc=樓梯通往更深處。
levels.level.exit_name=深度出口
levels.level.floor_name=地面
levels.level.furrowed_grass_name=溝壑狀植被
levels.level.grass_name=草
levels.level.hidden_trap=隱藏的 %s 啟動了！
levels.level.high_grass_desc=茂密的植被遮擋了視線。
levels.level.high_grass_name=高草
levels.level.inactive_trap_desc=這個陷阱以前觸發過，現在已經不危險了。
levels.level.inactive_trap_name=觸發陷阱
levels.level.locked_door_desc=這扇門鎖著，你需要一把相符的鑰匙才能打開。
levels.level.locked_door_name=鎖著的門
levels.level.locked_exit_desc=通往樓下的樓梯被厚重的鐵柵欄擋住了。
levels.level.locked_exit_name=鎖定深度出口
levels.level.open_door_name=打開門
levels.level.pedestal_name=座
levels.level.statue_desc=顯然，有人想裝飾這個地方，但失敗了。
levels.level.statue_name=雕像
levels.level.unlocked_exit_name=解鎖深度出口
levels.level.wall_name=牆
levels.level.water_desc=如果著火，請立即跳入水中滅火。
levels.level.water_name=水
levels.level.well_name=出色地
levels.mininglevel.barricade_desc=木製路障牢固地架設起來，支撐著天花板。這很可能是豺狼人建造的，用來抵禦落石。 _任何相鄰的牢房都將免受落石陷阱和攻擊。 _它看起來和其他路障一樣，很容易被燒毀。
levels.mininglevel.boulder_desc=有一塊巨石擋住了去路。用鎬應該很容易就能敲碎。
levels.mininglevel.boulder_name=博爾德
levels.mininglevel.crystal_desc=這裡有一塊豐碩的水晶露頭。這些水晶很脆弱，用鎬頭很容易就能敲碎，或者在它旁邊開採其他東西也會損壞它們。
levels.mininglevel.crystal_name=水晶尖刺
levels.mininglevel.gold_extra_desc=你大概可以用鎬把它挖出來。
levels.mininglevel.wall_desc=這是一面光滑的岩壁，比一般的岩壁略微柔軟一些。你可以用鎬子挖開它，但這會花費一些力氣，並且會稍微增加你的飢餓值。
levels.prisonlevel.bookshelf_desc=這很可能是監獄圖書館的遺跡。它會被燒毀嗎？
levels.prisonlevel.empty_deco_desc=地板上有陳舊的血跡。
levels.prisonlevel.region_deco_alt_desc=一個剛好能困住一個人的金屬籠子，用一條鍊子懸掛在深淵上方。
levels.prisonlevel.region_deco_alt_name=吊籠
levels.prisonlevel.region_deco_desc=一個剛好能困住一個人的金屬籠子。它似乎被某種方式固定在地面上，無法移動。
levels.prisonlevel.region_deco_name=監獄籠子
levels.prisonlevel.water_name=漆黑冰冷的水
levels.rooms.quest.ambitiousimproom$questentrance.desc=這個陰森森的深坑似乎是通往某個古老矮人寶庫的入口。一道魔法屏障阻止了進入，但你可以像走過地面一樣從屏障上方走過。
levels.rooms.quest.ambitiousimproom$questentrance.name=金庫入口
levels.rooms.quest.blacksmithroom$questentrance.desc=這架梯子通往鐵匠鋪正下方的一個廢棄礦坑。
levels.rooms.quest.blacksmithroom$questentrance.name=礦井入口
levels.rooms.quest.massgraveroom$bones.desc=地上散落著白骨，這裡到底發生了什麼事？
levels.rooms.quest.massgraveroom$bones.name=萬人坑
levels.rooms.quest.mineentrance$questexit.desc=這架梯子通往礦坑外，回到鐵匠鋪。
levels.rooms.quest.mineentrance$questexit.name=礦井出口
levels.rooms.quest.ritualsiteroom$ritualmarker.desc=這是用於某種黑暗儀式的彩繪標記。通常會在四個角落放置蠟燭。
levels.rooms.quest.ritualsiteroom$ritualmarker.name=儀式標記
levels.rooms.special.magicalfireroom$eternalfire.desc=這裡出現了一堵濃密的亮綠色火焰牆，似乎是由魔法造成的。火焰牆密度極高，根本無法穿過，而且任何靠近的東西都會被點燃。它沒有自然熄滅的跡象，你必須使用某種方法才能將其撲滅。
levels.rooms.special.sentryroom$sentry.desc=這個血紅色的哨兵似乎被安排在這裡守護房間另一端的寶藏。如果你踏入它守護的區域，它會向你發射分解魔法光束。它免疫所有有害效果，也能看穿隱形，但似乎需要一段時間充能才能開始攻擊。不知為何，這個哨兵似乎只想攻擊你，彷彿它知道地牢裡的居民對寶藏構不成威脅。
levels.rooms.special.sentryroom$sentry.discover_hint=你可以在地牢的任何地方遇到這種敵人。
levels.rooms.special.sentryroom$sentry.name=紅色哨兵
levels.rooms.special.toxicgasroom$toxicvent.desc=一定是某個粗心的冒險者很久以前觸發了這個陷阱。儘管它現在處於休眠狀態，但仍在向房間裡持續釋放毒氣，而且沒有停止的跡象。如果你想探索這個房間，你必須想辦法避免受到毒氣的傷害。
levels.rooms.special.toxicgasroom$toxicvent.name=有毒氣體排放
levels.rooms.special.weakfloorroom$hiddenwell.desc=你隱約能看到下方深處有一口井，也許下面有什麼東西？
levels.rooms.special.weakfloorroom$hiddenwell.name=遠處的井
levels.sewerlevel.bookshelf_desc=書架上堆滿了廉價無用的書。它會著火嗎？
levels.sewerlevel.empty_deco_desc=地板上覆蓋著潮濕的淡黃色苔蘚。
levels.sewerlevel.region_deco_desc=一個幾乎跟你一樣大的厚重木桶。它肯定裝滿了什麼東西，太重了，根本搬不動。
levels.sewerlevel.region_deco_name=收納桶
levels.sewerlevel.water_name=混濁的水
levels.traps.alarmtrap.alarm=陷阱發出刺耳的聲音，在整個地牢中迴盪！
levels.traps.alarmtrap.desc=這個陷阱似乎與一個響亮的警報裝置相連。觸發它很可能會驚動這層樓裡的所有人。
levels.traps.alarmtrap.name=警報陷阱
levels.traps.blazingtrap.desc=踩到這個陷阱會引燃強力化學混合物，引發大範圍火災。
levels.traps.blazingtrap.name=熾熱陷阱
levels.traps.burningtrap.desc=踩到這個陷阱會引燃化學混合物，使周圍區域燃起火焰。
levels.traps.burningtrap.name=燃燒陷阱
levels.traps.chillingtrap.desc=啟動後，該捕集器中的化學物質會迅速凍結其周圍空氣。
levels.traps.chillingtrap.name=令人不寒而慄的陷阱
levels.traps.confusiontrap.desc=觸發此陷阱會在附近區域釋放一團混亂氣體。
levels.traps.confusiontrap.name=混亂氣體陷阱
levels.traps.corrosiontrap.desc=觸發此陷阱會在附近區域釋放出一團致命的酸性氣體。
levels.traps.corrosiontrap.name=腐蝕性氣體捕集器
levels.traps.cursingtrap.curse=你破舊的裝備被詛咒了！
levels.traps.cursingtrap.desc=這個陷阱蘊含著與詛咒裝備相同的邪惡魔法。觸發它會詛咒周圍區域的一些物品。
levels.traps.cursingtrap.name=詛咒陷阱
levels.traps.disarmingtrap.desc=這個陷阱蘊含著非常特殊的傳送魔法，可以將受害者的武器傳送到其他地方。
levels.traps.disarmingtrap.disarm=你的武器被傳送走了！
levels.traps.disarmingtrap.name=解除陷阱
levels.traps.disintegrationtrap.desc=觸發後，此陷阱將向最近的目標發射分解光束，造成大量傷害並摧毀物品。值得慶幸的是，觸發機制並不隱藏。
levels.traps.disintegrationtrap.name=分解陷阱
levels.traps.disintegrationtrap.ondeath=你被分解陷阱殺死了…
levels.traps.disintegrationtrap.one=陷阱會摧毀你的 %s！
levels.traps.disintegrationtrap.some=陷阱會分解你的一些 %s！
levels.traps.distortiontrap.desc=這個陷阱由來已久的神秘魔法建造而成，它會將各種各樣的生物召喚到這裡來。
levels.traps.distortiontrap.name=失真陷阱
levels.traps.explosivetrap.desc=這個陷阱裡裝有粉狀炸藥和一個觸發裝置。啟動它會導致附近區域爆炸。
levels.traps.explosivetrap.name=爆炸陷阱
levels.traps.flashingtrap.desc=一旦啟動，此陷阱將引燃儲存在內部的強力閃光粉，使受害者暫時失明、喪失行動能力並受傷。此陷阱必須儲存大量的閃光粉，因為它可以多次啟動而不會損壞。
levels.traps.flashingtrap.name=閃光陷阱
levels.traps.flocktrap.desc=也許這是某個業餘魔法師開的一個玩笑，觸發這個陷阱會創造出一群魔法綿羊。
levels.traps.flocktrap.name=誘鳥陷阱
levels.traps.frosttrap.desc=啟動後，此捕集器中的化學物質會迅速凍結其周圍大範圍內的空氣。
levels.traps.frosttrap.name=霜凍陷阱
levels.traps.gatewaytrap.desc=這個特殊的傳送陷阱可以無限次觸發，每次都會傳送到同一個位置。
levels.traps.gatewaytrap.name=網關陷阱
levels.traps.geysertrap.desc=觸發此陷阱後，將噴出一股水柱，對火焰敵人造成傷害，擊退附近所有角色，撲滅火焰，並將周圍地形變成水。
levels.traps.geysertrap.name=間歇泉陷阱
levels.traps.gnollrockfalltrap.desc=這個落石陷阱是藉助某種魔法力量製造出來的。觸發後，它會使周圍5x5範圍內的岩石鬆動並立即從上方落下。由於該區域岩石較軟，它造成的傷害不如普通落石陷阱，但你的盔甲也無法抵擋。此外，如果附近有路障，岩石就不會落下，因為路障可以支撐頂部。這個陷阱無法區分敵我，因此對豺狼人和你一樣危險。
levels.traps.gnollrockfalltrap.name=豺狼人落石陷阱
levels.traps.grimtrap.desc=這個陷阱中蘊藏著威力極其強大的破壞性魔法，足以瞬間殺死除最強壯的英雄之外的所有人。觸發陷阱後，會向最近的角色發射一道致命的遠程魔法衝擊波。值得慶幸的是，觸發機制並不隱密。
levels.traps.grimtrap.name=殘酷陷阱
levels.traps.grimtrap.ondeath=你死於一個陰森陷阱的爆炸…
levels.traps.grippingtrap.desc=這種陷阱會抓住觸發者的腳，對其造成傷害並減緩其移動速度。由於其結構簡單，這種陷阱可以多次觸發而不會損壞。
levels.traps.grippingtrap.name=陷阱
levels.traps.guardiantrap$guardian.desc=這個藍色的幻影似乎是地牢中某個石像守衛的召喚迴響。
levels.traps.guardiantrap$guardian.desc_weapon=雖然雕像本身幾乎沒有實體，但它所揮舞的_%s_看起來卻很逼真。
levels.traps.guardiantrap$guardian.discover_hint=你可以透過特定的陷阱找到這個敵人。
levels.traps.guardiantrap$guardian.name=召喚守護者
levels.traps.guardiantrap.alarm=陷阱發出刺耳的聲音，在整個地牢中迴盪！
levels.traps.guardiantrap.desc=這個陷阱與一種奇特的魔法機制有關，它會召喚守護者並驚動該樓層的所有敵人。
levels.traps.guardiantrap.name=守護者陷阱
levels.traps.oozetrap.desc=這個陷阱啟動後會濺出腐蝕性液體，這些液體會燃燒直到被沖走。
levels.traps.oozetrap.name=洩漏陷阱
levels.traps.pitfalltrap.desc=這個陷阱連接著一個大型活板門裝置，觸發後不久，附近的任何東西都會直接穿過地面掉下去！不過，在地面特別堅實的地方，這個陷阱就不起作用了。
levels.traps.pitfalltrap.name=陷阱
levels.traps.pitfalltrap.no_pit=這裡地面太堅實，陷阱無法生效。
levels.traps.pitfalltrap.triggered=觸發陷阱後，地面開始塌陷！
levels.traps.pitfalltrap.triggered_hero=你周圍的地面開始塌陷！
levels.traps.poisondarttrap.desc=附近必須隱藏一個小型飛鏢發射器，啟動此陷阱後，它會向最近的目標發射一支毒鏢。值得慶幸的是，觸發裝置並沒有被隱藏。
levels.traps.poisondarttrap.name=毒鏢陷阱
levels.traps.poisondarttrap.ondeath=你被毒鏢陷阱殺死了…
levels.traps.rockfalltrap.desc=這個陷阱與上方的一系列鬆動岩石相連，觸發後這些岩石會轟然落下，覆蓋整個房間！如果陷阱不在特定房間內，岩石會落在陷阱周圍的區域。值得慶幸的是，觸發機制並不隱密。
levels.traps.rockfalltrap.name=落石陷阱
levels.traps.rockfalltrap.ondeath=你被落石陷阱砸中了…
levels.traps.shockingtrap.desc=這是一個儲存了大量能量的裝置。觸發這個陷阱會將能量釋放到周圍的能量場。
levels.traps.shockingtrap.name=令人震驚的陷阱
levels.traps.stormtrap.desc=這是一個儲存著巨大能量的裝置。觸發這個陷阱會將這些能量釋放成一場巨大的雷雨。
levels.traps.stormtrap.name=風暴陷阱
levels.traps.summoningtrap.desc=觸發此陷阱會將此區域的許多怪物召喚到這裡。
levels.traps.summoningtrap.name=召喚陷阱
levels.traps.teleportationtrap.desc=當這個陷阱被觸發時，它周圍的所有東西都會被傳送到這一層的隨機位置。
levels.traps.teleportationtrap.name=傳送陷阱
levels.traps.tengudarttrap.desc=天狗顯然一直在備戰。這個陷阱會啟動一個隱藏的飛鏢發射器，向除了天狗以外的任何物體發射毒鏢。這個陷阱製作得非常精巧，沒有魔法的幫助根本無法察覺其觸發機制。不過，陷阱在設置過程中會短暫地顯露出來。
levels.traps.toxictrap.desc=觸發此陷阱會在周圍區域釋放一團有毒氣體。
levels.traps.toxictrap.name=有毒氣體捕集器
levels.traps.trap.discover_hint=這種陷阱會在地牢中隨機出現。每個區域出現的陷阱都不一樣。
levels.traps.trap.rankings_desc=被 %s 殺死
levels.traps.warpingtrap.desc=這個陷阱類似於傳送陷阱，但還會讓英雄失去對樓層佈局的了解！
levels.traps.warpingtrap.name=扭曲陷阱
levels.traps.weakeningtrap.desc=這個陷阱中的黑暗魔法會吸取任何接觸到它的東西的能量。不過，強大的敵人或許能夠抵抗這種效果。
levels.traps.weakeningtrap.name=削弱陷阱
levels.traps.worndarttrap.desc=附近必須藏著一個小型飛鏢發射器，啟動這個陷阱後，它會向最近的目標發射飛鏢。 \n\n由於年代久遠，它其實危害不大，甚至都沒藏起來…
levels.traps.worndarttrap.name=磨損的飛鏢陷阱
levels.traps.worndarttrap.ondeath=你被那破舊的飛鏢陷阱殺死了…
levels.vaultlevel$vaultflametrap.desc=這個通風口似乎會定時噴出綠色火焰。 _由於這只是一個測試區域，通風口噴出的火焰不會對您造成實際傷害。 _
levels.vaultlevel$vaultflametrap.name=拱頂火焰排放口
