windows.wndblacksmith$hardenselector.prompt=強化物品
windows.wndblacksmith$upgradeselector.prompt=升級物品
windows.wndblacksmith$wndreforge.message=好的，我可以重鑄兩件同類型的已鑑定物品。較弱的那件會被摧毀，用來升級較強的那件。如果它們的等級相同，我會保留左邊那件。
windows.wndblacksmith$wndreforge.prompt=重鑄物品
windows.wndblacksmith$wndreforge.reforge=重鑄它們
windows.wndblacksmith$wndsmith.prompt=好了，這是我能做的東西。我已經把爐子點起來了，你們快點選吧。
windows.wndblacksmith.cashout=_兌現（所有好感度）：_我可以給你一些我手邊閒置的普通金幣。每點好感度給你1個金幣。
windows.wndblacksmith.cashout_no=沒關係。
windows.wndblacksmith.cashout_verify=好了，這就是%d金幣。不過之後我不會再為你做任何事了！
windows.wndblacksmith.cashout_yes=把金子給我。
windows.wndblacksmith.harden=_強化（%d 恩惠）：_ 我可以強化武器或盔甲，使其更容易保持附魔或符文的效果。
windows.wndblacksmith.pickaxe=鎬（%d 恩惠）：如果你想要的話，我可以把鎬還給你。我還有很多。
windows.wndblacksmith.pickaxe_free=嗯，你做得相當不錯，我免費送給你。
windows.wndblacksmith.pickaxe_no=沒關係。
windows.wndblacksmith.pickaxe_verify=你確定要這件舊東西嗎？這附近的岩石不像礦井裡的那麼軟，所以你用它沒辦法再挖東西了。
windows.wndblacksmith.pickaxe_yes=是的，我想要。
windows.wndblacksmith.prompt=好了，一言既出，驛馬難追。以下是我能為你做的。我只處理已鑑定且未被詛咒的物品。目前恩惠：\n\n_
windows.wndblacksmith.reforge=_重鑄（%d 恩惠）：_我可以將兩個相同類型的物品重鑄成一個更高品質的物品。
windows.wndblacksmith.smith=史密斯（%d 恩惠）：我可以嘗試從零開始為你打造一件武器或盔甲。它會是更高等級的，而且很可能是升級過的，你也可以選擇你想要的款式。
windows.wndblacksmith.smith_no=沒關係。
windows.wndblacksmith.smith_verify=好的，我這就把鍛爐預熱，然後你就可以挑選你想要的了。
windows.wndblacksmith.smith_yes=好了，開始預熱鍛爐。
windows.wndblacksmith.upgrade=_升級（%d 恩惠）：_ 如果你的物品等級低於 +2，我可以幫你升級。
windows.wndchallenges.title=挑戰
windows.wndchooseability.are_you_sure=你確定要選擇這項技能嗎？
windows.wndchooseability.cancel=我稍後再決定。
windows.wndchooseability.message=王冠戴在你的頭上時發出光芒，王冠和你的盔甲都變得滾燙。你能感覺到王冠的魔法開始作用於你的盔甲，但這股力量必須由你掌控。你會選擇哪一種盔甲能力？
windows.wndchooseability.message_no_crown=選擇一種盔甲技能！
windows.wndchooseability.no=不，我稍後再決定。
windows.wndchooseability.random_sure=你確定要隨機選擇你的護甲技能嗎？
windows.wndchooseability.random_title=隨機護甲能力
windows.wndchooseability.yes=是的，我已經做出了選擇。
windows.wndchoosesubclass.are_you_sure=您確定要選擇這個子類別嗎？
windows.wndchoosesubclass.cancel=我稍後再決定。
windows.wndchoosesubclass.message=面具戴在臉上後，你的視力逐漸模糊，腦海中湧現新的力量景象。你將如何駕馭這股力量？
windows.wndchoosesubclass.no=不，我稍後再決定。
windows.wndchoosesubclass.random_sure=你確定要隨機選擇一個子類別嗎？
windows.wndchoosesubclass.random_title=隨機子類
windows.wndchoosesubclass.yes=是的，我已經做出了選擇。
windows.wndclass.mastery=精通
windows.wndclericspells.cast=投擲
windows.wndclericspells.cast_desc_desktop=選擇法術進行施放，右鍵點選查看訊息或將法術設定為快速施放。
windows.wndclericspells.cast_desc_mobile=選擇法術進行施放，長按可設定法術快速施放，或按資訊按鈕切換至資訊模式。
windows.wndclericspells.cast_title=施法
windows.wndclericspells.info=資訊
windows.wndclericspells.info_desc=選擇法術以了解其相關訊息，或按下聖書按鈕切換到施法模式。
windows.wndclericspells.info_title=拼字訊息
windows.wndclericspells.quick_cast=快速投擲
windows.wndcombo.combo_req=（%d 組合）
windows.wndcombo.title=選擇連擊招式
windows.wnddailies.date=日期
windows.wnddailies.score=分數
windows.wnddailies.title=每日歷史
windows.wnddocument.missing=頁面缺失
windows.wndenergizeitem.energize=轉化為 %d 能量
windows.wndenergizeitem.energize_1=將 1 轉化為 %d 能量
windows.wndenergizeitem.energize_all=將所有能量轉換為 %d 能量
windows.wndenergizeitem.prompt=啟動物品
windows.wndenergizeitem.trinket_no=不，算了。
windows.wndenergizeitem.trinket_warn=你確定要給你的飾品充能嗎？你會恢復5點能量，但飾品會永久消失！
windows.wndenergizeitem.trinket_yes=是的，激活它
windows.wnderror.title=錯誤
windows.wndgame.challenges=挑戰
windows.wndgame.exit=退出遊戲
windows.wndgame.menu=主選單
windows.wndgame.rankings=排名
windows.wndgame.return=返回遊戲
windows.wndgame.settings=設定
windows.wndgame.start=開始新遊戲
windows.wndgameinprogress.challenges=挑戰
windows.wndgameinprogress.continue=繼續
windows.wndgameinprogress.custom_seed=自訂種子
windows.wndgameinprogress.daily_for=每日精選
windows.wndgameinprogress.depth=最大深度
windows.wndgameinprogress.dungeon_seed=地城種子
windows.wndgameinprogress.erase=擦除
windows.wndgameinprogress.erase_warn_body=這款遊戲的所有進度都將失去。
windows.wndgameinprogress.erase_warn_no=不，我想繼續
windows.wndgameinprogress.erase_warn_title=您確定要刪除此存檔嗎？
windows.wndgameinprogress.erase_warn_yes=是的，刪除此存檔
windows.wndgameinprogress.exp=經驗
windows.wndgameinprogress.gold=收集的黃金
windows.wndgameinprogress.health=健康
windows.wndgameinprogress.replay_for=_重播_
windows.wndgameinprogress.str=力量
windows.wndgameinprogress.title=等級 %1$d %2$s
windows.wndhero$statstab.custom_seed=自訂種子
windows.wndhero$statstab.daily_for=每日精選
windows.wndhero$statstab.depth=最大深度
windows.wndhero$statstab.dungeon_seed=地城種子
windows.wndhero$statstab.exp=經驗
windows.wndhero$statstab.gold=收集的黃金
windows.wndhero$statstab.health=健康
windows.wndhero$statstab.replay_for=_重播_
windows.wndhero$statstab.str=力量
windows.wndhero$statstab.title=等級 %1$d %2$s
windows.wndhero.buffs=巴夫斯
windows.wndhero.stats=統計數據
windows.wndhero.talents=天賦
windows.wndheroinfo.abilities=護甲能力
windows.wndheroinfo.abilities_msg=擊敗第四個 Boss 後可以選擇一種護甲能力。
windows.wndheroinfo.subclasses=子類別
windows.wndheroinfo.subclasses_msg=擊敗第二個 Boss 後可以選擇子職業。
windows.wndheroinfo.talents=天賦
windows.wndheroinfo.talents_msg=英雄每次升級都會獲得一點天賦點數。擊敗第二個首領後，即可解鎖更高階的天賦。
windows.wndimp.message=哦耶！你真是我的英雄！至於你的賞賜，我現在身上沒有現金，但我有更好的東西給你。這是我家的傳家戒指：我爺爺從一位陣亡聖騎士的手指上取下來的。
windows.wndimp.reward=拿起戒指
windows.wndinfocell.nothing=沒什麼有趣的。
windows.wndinfotalent.upgrade=提升人才
windows.wndinfotrap.inactive=此陷阱已失效，無法再被觸發。
windows.wndjournal$alchemytab.title=煉金術指南
windows.wndjournal$badgestab.overall=全面的
windows.wndjournal$badgestab.this_run=本次跑步
windows.wndjournal$badgestab.title=徽章
windows.wndjournal$badgestab.title_main_menu=你的徽章
windows.wndjournal$catalogtab.enemy_count=你總共擊敗過這個敵人 _%,d_ 次。
windows.wndjournal$catalogtab.energy_count=您總共使用了 _%,d_ 個能量晶體。
windows.wndjournal$catalogtab.gold_count=您總共花了 _%,d_ 金幣。
windows.wndjournal$catalogtab.not_seen_ally=你之前的所有遊戲中都沒有遇過這個角色。
windows.wndjournal$catalogtab.not_seen_enchantment=你至今為止的所有探索中還沒有找到並鑑定出帶有該附魔的武器。
windows.wndjournal$catalogtab.not_seen_enemy=你之前的所有挑戰都沒有擊敗過這個敵人。
windows.wndjournal$catalogtab.not_seen_glyph=你至今為止還沒有在任何一次探索中找到並鑑定出帶有該符文的盔甲。
windows.wndjournal$catalogtab.not_seen_item=你尚未在任何一次探索中找到並識別出該物品。
windows.wndjournal$catalogtab.not_seen_lore=你之前的所有冒險中都沒有找到過這段背景故事文本。
windows.wndjournal$catalogtab.not_seen_plant=你之前的任何一次跑步中都沒有檢查或踩踏過這種植物。
windows.wndjournal$catalogtab.not_seen_trap=你還沒有在任何一次運行中檢查或觸發過這個陷阱。
windows.wndjournal$catalogtab.plant_count=你總共踐踏了這株植物_%,d_次。
windows.wndjournal$catalogtab.title=產品目錄
windows.wndjournal$catalogtab.title_bestiary=動物寓言集
windows.wndjournal$catalogtab.title_consumables=消耗品
windows.wndjournal$catalogtab.title_equipment=裝置
windows.wndjournal$catalogtab.title_lore=知識
windows.wndjournal$catalogtab.trap_count=您已觸發此陷阱共 _%,d_ 次。
windows.wndjournal$catalogtab.trinket_count=您總共製作或升級過此物品 _%,d_ 次。
windows.wndjournal$catalogtab.upgrade_count=您已將此物品升級了 _%,d_ 次。
windows.wndjournal$catalogtab.use_count=您已使用此物品共 _%,d_ 次。
windows.wndjournal$guidetab.missing=頁面缺失
windows.wndjournal$guidetab.title=地下城指南
windows.wndjournal$notestab.custom_notes=風俗
windows.wndjournal$notestab.desc=當你探索地牢時，你會自動在這裡記錄值得注意的事情。
windows.wndjournal$notestab.floor_header=樓層 %d
windows.wndjournal$notestab.title=冒險筆記
windows.wndkeybindings$wndchangebinding.cancel=取消
windows.wndkeybindings$wndchangebinding.cant_unbind=此操作必須綁定至少一個按鍵。
windows.wndkeybindings$wndchangebinding.changed_bind=新綁定：_%s_
windows.wndkeybindings$wndchangebinding.confirm=確認
windows.wndkeybindings$wndchangebinding.desc_current=目前綁定：_%s_
windows.wndkeybindings$wndchangebinding.desc_first=按任意鍵可變更下列按鍵的第一個綁定：_%s_。
windows.wndkeybindings$wndchangebinding.desc_second=按任意鍵可變更以下第二個按鍵綁定：_%s_。
windows.wndkeybindings$wndchangebinding.desc_third=按任意鍵可變更第三個按鍵綁定：_%s_。
windows.wndkeybindings$wndchangebinding.error=此密鑰已綁定到此操作。
windows.wndkeybindings$wndchangebinding.unbind=解除綁定鍵
windows.wndkeybindings$wndchangebinding.warning=此金鑰將從 _%s_ 解除綁定。
windows.wndkeybindings.back=後退
windows.wndkeybindings.bag_1=容器 1
windows.wndkeybindings.bag_2=容器 2
windows.wndkeybindings.bag_3=3號貨櫃
windows.wndkeybindings.bag_4=4號貨櫃
windows.wndkeybindings.bag_5=5號貨櫃
windows.wndkeybindings.cancel=取消
windows.wndkeybindings.confirm=確認
windows.wndkeybindings.controller_info=左搖桿控制角色移動，右搖桿控制螢幕上的指針
windows.wndkeybindings.cycle=下一個目標/下一個標籤頁
windows.wndkeybindings.default=預設綁定
windows.wndkeybindings.e=東
windows.wndkeybindings.examine=檢查
windows.wndkeybindings.hero_info=英雄訊息
windows.wndkeybindings.inventory=存貨
windows.wndkeybindings.inventory_selector=庫存選擇器
windows.wndkeybindings.journal=雜誌
windows.wndkeybindings.left_click=左鍵點選
windows.wndkeybindings.menu=選單
windows.wndkeybindings.middle_click=中鍵點擊
windows.wndkeybindings.n=向北
windows.wndkeybindings.ne=向東北方向
windows.wndkeybindings.none=沒有任何
windows.wndkeybindings.nw=向西北方向走
windows.wndkeybindings.quickslot_1=快捷欄 1
windows.wndkeybindings.quickslot_2=快速欄 2
windows.wndkeybindings.quickslot_3=快捷欄 3
windows.wndkeybindings.quickslot_4=快速欄 4
windows.wndkeybindings.quickslot_5=快速欄 5
windows.wndkeybindings.quickslot_6=快捷欄 6
windows.wndkeybindings.quickslot_selector=快速槽選擇器
windows.wndkeybindings.rest=休息
windows.wndkeybindings.right_click=右鍵單擊
windows.wndkeybindings.s=往南走
windows.wndkeybindings.se=前往東南
windows.wndkeybindings.sw=向西南方向
windows.wndkeybindings.tag_action=特別行動
windows.wndkeybindings.tag_attack=攻擊敵人
windows.wndkeybindings.tag_danger=切換敵人
windows.wndkeybindings.tag_loot=取貨物品
windows.wndkeybindings.tag_resume=恢復運動
windows.wndkeybindings.ttl_action=行動
windows.wndkeybindings.ttl_key1=關鍵點 1
windows.wndkeybindings.ttl_key2=關鍵點 2
windows.wndkeybindings.ttl_key3=關鍵點 3
windows.wndkeybindings.w=向西
windows.wndkeybindings.wait=等待
windows.wndkeybindings.wait_or_pickup=等待/取貨
windows.wndkeybindings.zoom_in=放大/向下滾動
windows.wndkeybindings.zoom_out=縮小/向上滾動
windows.wndmonkabilities.energycost=（%d 能量）
windows.wndmonkabilities.title=選擇一項能力
windows.wndquickbag.title=快速使用物品
windows.wndranking$statstab.alchemy=製作物品
windows.wndranking$statstab.ascent=最高海拔
windows.wndranking$statstab.challenges=挑戰
windows.wndranking$statstab.copy_seed=複製種子
windows.wndranking$statstab.copy_seed_cancel=取消
windows.wndranking$statstab.copy_seed_copy=使用此種子
windows.wndranking$statstab.custom_seed=自訂種子
windows.wndranking$statstab.daily_for=每日精選
windows.wndranking$statstab.depth=最大深度
windows.wndranking$statstab.duration=遊戲時長
windows.wndranking$statstab.enemies=暴徒被殺
windows.wndranking$statstab.food=吃的食物
windows.wndranking$statstab.gold=收集的黃金
windows.wndranking$statstab.replay_for=_重播_
windows.wndranking$statstab.score=分數
windows.wndranking$statstab.seed=地城種子
windows.wndranking$statstab.str=力量
windows.wndranking$statstab.talents=天賦
windows.wndranking$statstab.title=等級 %1$d %2$s
windows.wndranking.badges=徽章
windows.wndranking.error=無法加載更多信息
windows.wndranking.items=專案
windows.wndranking.stats=統計數據
windows.wndresurrect.confirm=請保存這些物品
windows.wndresurrect.message=當你瀕臨死亡之際，你能感受到你的生命之符（ankh）指引你的靈魂重返人間。它給了你再次征服地牢的機會！你可以帶走兩件物品，其餘的則會留在你隕落的地方。你會選擇哪些物品？
windows.wndresurrect.prompt=選擇一個項目
windows.wndresurrect.title=復活
windows.wndresurrect.warn_body=您尚未選擇兩件物品。您確定要在不選擇兩件物品的情況下復活嗎？
windows.wndresurrect.warn_no=不，讓我重新考慮一下。
windows.wndresurrect.warn_title=缺物品
windows.wndresurrect.warn_yes=是的，我確定
windows.wndsadghost.cancel=取消
windows.wndsadghost.confirm=確認
windows.wndsadghost.crab=謝謝，那隻巨蟹終於被消滅了，我可以休息了……真想知道它究竟用了什麼邪惡的魔法，才能活那麼久……
windows.wndsadghost.crab_title=打敗巨蟹
windows.wndsadghost.farewell=再見了，冒險家！
windows.wndsadghost.give_item=請拿走其中一件，它們現在對我來說沒用了……或許它們能對你的旅程有所幫助……\n\n另外……這地牢裡遺失了一件我非常珍惜的物品……如果你……找到了我的……玫瑰……
windows.wndsadghost.gnoll=謝天謝地，那個陰險的豺狼人終於被幹掉了，我可以休息了……真想知道是什麼樣的邪惡魔法讓它如此聰明……
windows.wndsadghost.gnoll_title=擊敗豺狼騙子
windows.wndsadghost.rat=謝謝，那隻可惡的老鼠終於被消滅了，我終於可以休息了……真想知道是什麼樣的邪惡魔法創造瞭如此醜陋的生物……
windows.wndsadghost.rat_title=被打敗的臭老鼠
windows.wndscorebreakdown.bosses_desc=根據擊敗的 Boss 數量計算。 Boss 戰中若站在可躲避的攻擊下會減少。
windows.wndscorebreakdown.bosses_title=老闆
windows.wndscorebreakdown.challenge_multiplier=挑戰倍率
windows.wndscorebreakdown.explore_desc=根據已探索樓層數計算。扣除遺漏物品、隱藏門或未解謎題造成的損失。
windows.wndscorebreakdown.explore_title=勘探
windows.wndscorebreakdown.old_score_desc=v1.3 版本之前開始的遊戲得分類別較少，但遊戲進度大約增加了 50%，寶藏上限也更高。
windows.wndscorebreakdown.progress_desc=基於最大深度和英雄等級。
windows.wndscorebreakdown.progress_title=進展
windows.wndscorebreakdown.quests_desc=根據完成的任務數量計算。受到可避免的攻擊或任務得分低於目標分數會降低數值。
windows.wndscorebreakdown.quests_title=任務
windows.wndscorebreakdown.title=得分明細
windows.wndscorebreakdown.total=總分
windows.wndscorebreakdown.treasure_desc=基於收集的黃金和持有的物品價值。
windows.wndscorebreakdown.treasure_desc_old=根據收集到的黃金數量計算。
windows.wndscorebreakdown.treasure_title=寶藏
windows.wndscorebreakdown.win_multiplier=獲勝倍率
windows.wndsettings$audiotab.ignore_silent=忽略靜默模式
windows.wndsettings$audiotab.music_bg=背景音樂播放
windows.wndsettings$audiotab.music_mute=靜音音樂
windows.wndsettings$audiotab.music_vol=音樂音量
windows.wndsettings$audiotab.sfx_mute=靜音音效
windows.wndsettings$audiotab.sfx_vol=音效音量
windows.wndsettings$audiotab.title=音訊設定
windows.wndsettings$datatab.betas=包含測試版更新
windows.wndsettings$datatab.news=查看新聞
windows.wndsettings$datatab.title=連接設定
windows.wndsettings$datatab.updates=請檢查更新
windows.wndsettings$datatab.wifi=僅檢查 WiFi
windows.wndsettings$displaytab.bright=明亮的
windows.wndsettings$displaytab.brightness=亮度
windows.wndsettings$displaytab.camera_follow=攝影機跟隨強度
windows.wndsettings$displaytab.cancel=取消
windows.wndsettings$displaytab.dark=黑暗的
windows.wndsettings$displaytab.fullscreen=全螢幕
windows.wndsettings$displaytab.hide_gesture=隱藏手勢欄
windows.wndsettings$displaytab.hide_navigation=隱藏導覽列
windows.wndsettings$displaytab.high=高的
windows.wndsettings$displaytab.landscape=力景觀
windows.wndsettings$displaytab.low=低的
windows.wndsettings$displaytab.off=離開
windows.wndsettings$displaytab.okay=好的
windows.wndsettings$displaytab.screenshake=螢幕搖晃
windows.wndsettings$displaytab.title=顯示設定
windows.wndsettings$displaytab.visual_grid=可視化網格
windows.wndsettings$inputtab.controller_bindings=控制器綁定
windows.wndsettings$inputtab.controller_sensitivity=控制器指針靈敏度
windows.wndsettings$inputtab.high=高的
windows.wndsettings$inputtab.key_bindings=按鍵綁定
windows.wndsettings$inputtab.movement_sensitivity=按住移動靈敏度
windows.wndsettings$inputtab.off=離開
windows.wndsettings$inputtab.title=輸入設定
windows.wndsettings$langstab.completed=該語言已完全翻譯並審核。
windows.wndsettings$langstab.credits=學分
windows.wndsettings$langstab.reviewers=評論員
windows.wndsettings$langstab.title=語言設定
windows.wndsettings$langstab.transifex=所有翻譯均由 Transifex 的志工提供。
windows.wndsettings$langstab.translators=譯者
windows.wndsettings$langstab.unfinished=_此語言尚未完全翻譯。 _ 大量文字可能仍為英文。
windows.wndsettings$langstab.unreviewed=此語言版本尚未經過審核。可能有錯誤，但所有文字均已翻譯。
windows.wndsettings$uitab.center=中心
windows.wndsettings$uitab.flip_indicators=翻轉指標
windows.wndsettings$uitab.flip_toolbar=翻轉工具列
windows.wndsettings$uitab.full=滿的
windows.wndsettings$uitab.group=團體
windows.wndsettings$uitab.high=高的
windows.wndsettings$uitab.mobile=移動的
windows.wndsettings$uitab.mode=工具列模式：
windows.wndsettings$uitab.off=離開
windows.wndsettings$uitab.quickslot_swapper=快速槽位交換器
windows.wndsettings$uitab.scale=界面尺度
windows.wndsettings$uitab.split=分裂
windows.wndsettings$uitab.swapper_desc=如果空間不足以顯示全部六個快捷欄，則顯示 3 個快捷欄，並帶有「交換」按鈕。
windows.wndsettings$uitab.system_font=系統字體
windows.wndsettings$uitab.title=介面設定
windows.wndsettings$uitab.toolbar_settings=工具列設定
windows.wndsettings$uitab.ui_mode=介面模式
windows.wndsettings$uitab.vibration=振動
windows.wndsupportprompt.close=關閉
windows.wndsupportprompt.title=來自開發者的消息
windows.wndtradeitem.buy=購買 %dg
windows.wndtradeitem.sell=出售 %dg
windows.wndtradeitem.sell_1=出售 1 件，售價為 %dg
windows.wndtradeitem.sell_all=全部出售，售價為 %dg
windows.wndtradeitem.steal=偷竊機會：%1$d%% 已用充能次數：%2$d
windows.wndtradeitem.steal_warn=你的手環電量不足，無法保證成功偷竊此物品。如果失敗，商店將會關門。你確定要嘗試偷竊嗎？
windows.wndtradeitem.steal_warn_no=不，我改變主意了。
windows.wndtradeitem.steal_warn_yes=是的，我確定
windows.wndupgrade.back=後退
windows.wndupgrade.bleeding=出血
windows.wndupgrade.blocking=阻塞
windows.wndupgrade.charges=最高收費
windows.wndupgrade.corrosion_damage=腐蝕損傷
windows.wndupgrade.curse_infusion=如果詛咒解除，該物品將不再受益於詛咒灌注！
windows.wndupgrade.cursed=升級此物品還有 33% 的幾率可以清除其詛咒。
windows.wndupgrade.cursed_weaken=升級此物品還可以削弱其詛咒效果，並且有 33% 的幾率完全清除詛咒。
windows.wndupgrade.damage=損害
windows.wndupgrade.dart_damage=飛鏢傷害
windows.wndupgrade.desc=升級物品可以永久提升其效能：
windows.wndupgrade.durability=耐久性
windows.wndupgrade.enchant=升級此物品也有 %d%% 的幾率破壞其附魔！
windows.wndupgrade.glyph=升級此物品還有 %d%% 的幾率摧毀其符文！
windows.wndupgrade.harden=升級此物品還有 %d%% 的幾率打破其硬化效果！
windows.wndupgrade.quantity=數量
windows.wndupgrade.remaining=您還剩下 _%d_ 個升級項目。
windows.wndupgrade.resin=這根魔杖已經用神秘樹脂強化過，一般升級會覆蓋樹脂升級的效果！
windows.wndupgrade.ring_boost=戒指加速
windows.wndupgrade.thrown_dust=該套裝中的武器如果不在你的物品欄中，將會化為塵埃。
windows.wndupgrade.title=升級物品
windows.wndupgrade.unided=你不知道這個物品的屬性，這裡顯示的是它未升級的狀態。
windows.wndupgrade.unknown_ring=你不知道這枚戒指的效果是什麼，所以也不知道升級它會帶來什麼好處。
windows.wndupgrade.upgrade=升級
windows.wndupgrade.ward_damage=守衛傷害
windows.wndupgrade.weight=重量
windows.wndupgrade.zap_damage=電擊傷害
windows.wndvictorycongrats.challenges=現在您可以啟用_挑戰！ _ 這些是可選的修改器，可以從各個方面增加遊戲的難度。
windows.wndvictorycongrats.close=關閉
windows.wndvictorycongrats.custom_seeds=現在你可以輸入自訂種子了！相同的種子和遊戲版本總是會生成相同的地下城。
windows.wndvictorycongrats.dailies=現在你可以參加每日挑戰囉！每天都會有新的每日挑戰，所有玩家的挑戰內容都一樣！
windows.wndvictorycongrats.start_text=恭喜你征服了地下城！你解鎖了一些新功能，這些功能會在你選擇英雄時啟用：
windows.wndvictorycongrats.support=支援
windows.wndvictorycongrats.support_prompt=如果您還沒有支援這款遊戲，請考慮支持一下。玩家的支持能讓開發者繼續改進遊戲！
windows.wndvictorycongrats.title=勝利！
windows.wndwandmaker.berry=哦，我看到你拿到漿果了！希望那株腐爛漿果不會給你帶來太多麻煩。正如我承諾的，你可以從我這裡挑選一根高品質的魔杖。
windows.wndwandmaker.dust=哦，我看到你帶了塵晶！別擔心那些幽靈，我可以對付它們。正如我承諾的，你可以從我這裡挑選一根高品質的魔杖。
windows.wndwandmaker.ember=哦，我看到你還有餘燼！希望火元素沒給你太大麻煩。正如我承諾的，你可以從我這裡挑選一根高品質的魔杖。
windows.wndwandmaker.farewell=祝你探險順利，%s！
windows.wndkeybindings.enter_door=進入門
windows.wndkeybindings.jump=跳
windows.wndkeybindings.press_or_click=按下或點擊
windows.wndkeybindings.quickslot_7=快捷欄 7
windows.wndkeybindings.ranged=遠端
