plants.blandfruitbush$seed.name=淡果的種子
plants.blandfruitbush.desc=這種與腐爛漿果有遠親關係的植物，結出的梨形果實味道像結塊的灰塵。果實口感糟糕且缺乏實質，但無毒。或許可以煮熟食用。
plants.blandfruitbush.discover_hint=這種植物有幾率在地牢中隨機出現。
plants.blandfruitbush.name=淡果
plants.blindweed$seed.name=盲草的種子
plants.blindweed.desc=盲草一旦被觸碰，便會在一道強光中消逝。這道閃光強度足以使人眩暈數秒。
plants.blindweed.name=盲草
plants.blindweed.warden_desc=守衛者會將盲草的能量轉化為暫時的隱形狀態，而不是迷失方向。
plants.earthroot$armor.desc=一種由樹皮和麻繩製成的天然固定盔甲。這種草藥盔甲可以抵抗任何物理攻擊造成的傷害，直到耐久度耗盡並最終崩解。由於盔甲無法移動，移動會導致它破碎並丟失。剩餘盔甲數量：
plants.earthroot$armor.name=草本護甲
plants.earthroot$seed.name=地根種子
plants.earthroot.desc=當生物接觸到土根時，土根會在生物周圍形成一種不可移動的天然盔甲。
plants.earthroot.name=地根
plants.earthroot.warden_desc=土根植物的根系會隨著守望者移動，為她提供可移動的樹皮護甲。
plants.fadeleaf$seed.name=淡葉種子
plants.fadeleaf.desc=觸碰到褪色葉會將任何生物傳送到目前關卡的隨機位置。
plants.fadeleaf.name=褪色葉
plants.fadeleaf.warden_desc=淡葉的傳送效果對守望者來說更加強大，可以將她傳送回上一層地牢的盡頭。
plants.firebloom$seed.name=火花種子
plants.firebloom.desc=當物體碰到火焰花時，就會燃起火焰。
plants.firebloom.name=火花
plants.firebloom.warden_desc=當她踩到火花時，守衛者會短暫地被火焰包裹，而不是受到傷害。
plants.icecap$seed.name=冰蓋種子
plants.icecap.desc=冰蓋被觸碰時會釋放出一團凍結的花粉。如果環境潮濕，這種凍結效果會更強。
plants.icecap.name=冰蓋
plants.icecap.warden_desc=當她踐踏冰蓋時，守衛者會短暫地被冰霜包裹，而不是受到傷害。
plants.mageroyal$seed.name=馬格羅伊爾的種子
plants.mageroyal.desc=馬格羅亞爾帶刺的花朵中含有一種化學物質，這種物質以其強大的中和作用而聞名。任何接觸到這種植物的東西都會被清除許多負面影響。
plants.mageroyal.name=馬格羅伊爾
plants.mageroyal.refreshed=你感覺神清氣爽。
plants.mageroyal.warden_desc=除了中和效果外，當守衛者踩到魔法寶地時，他將暫時免疫所有區域效果。
plants.plant$seed$placeholder.name=種子
plants.plant$seed.ac_plant=植物
plants.plant$seed.info=把這顆種子撒在你想種植物的地方。
plants.plant$seed.seed_of=%s 的種子
plants.plant.discover_hint=你可以在地牢中隨機找到這種植物，或者用它的種子種植它。
plants.plant.warden_desc=這種植物對典獄長來說並沒有什麼特殊效果。
plants.rotberry$seed.discover_hint=你可以在特定任務中找到這件物品。
plants.rotberry$seed.name=腐爛漿果的種子
plants.rotberry.desc=幼小的腐莓灌木的果實嘗起來就像甜蜜的死亡。幾年後，這棵腐莓灌木會長成另一棵腐爛的樹。幼小的腐莓被踩踏時，會釋放出一小團有毒氣體。
plants.rotberry.discover_hint=在特定任務中，你可以用對應的種子種植這種植物。
plants.rotberry.name=爛莓
plants.rotberry.warden_desc=通常情況下，腐爛漿果灌木被踩踏時只會產生少量氣體，但_守衛者_能夠從中汲取能量，暫時增強自己的力量！
plants.sorrowmoss$seed.name=哀苔的種子
plants.sorrowmoss.desc=哀苔是一種花（不是苔蘚），它的花瓣像剃刀一樣鋒利，並塗有致命的毒液。
plants.sorrowmoss.name=悲傷苔蘚
plants.sorrowmoss.warden_desc=當她踩到悲傷苔蘚時，守護者會短暫地被毒素浸染，而不是受到傷害。
plants.starflower$seed.name=星花種子
plants.starflower.desc=星花是一種罕見的植物，據說觸摸它的人會獲得神聖的力量。
plants.starflower.name=星花
plants.starflower.warden_desc=除了獲得祝福之外，當守望者踩踏星花時，她還會獲得大量的魔杖充能。
plants.stormvine$seed.name=暴風藤種子
plants.stormvine.desc=重力對風暴藤蔓植物的影響十分奇特，它那飄逸的藍色卷鬚能夠「懸掛」在空中。任何被藤蔓纏住的東西都會受到影響，變得迷失方向。
plants.stormvine.name=暴藤
plants.stormvine.warden_desc=守衛者能夠控制風暴藤蔓的引力效應，當她踩到風暴藤蔓時，會短暫懸浮。
plants.sungrass$health.desc=太陽草具有極佳的治療效果，但其治療速度遠不及治療藥水。離開植物會中斷治療效果。剩餘治療量：
plants.sungrass$health.name=草藥療法
plants.sungrass$seed.name=太陽草種子
plants.sungrass.desc=太陽草因其汁液具有緩慢但有效的癒合功效而聞名。
plants.sungrass.name=墨草
plants.sungrass.warden_desc=即使守衛者遠離被踐踏的太陽草，她仍然可以從中獲得治療。
plants.swiftthistle$seed.name=薊籽
plants.swiftthistle$timebubble.desc=加速時間的小氣泡，允許動作瞬間執行。但是攻擊或使用魔法會打破這種效果。剩餘回合數：\n\n。
plants.swiftthistle$timebubble.name=時間氣泡
plants.swiftthistle.desc=當被踐踏時，迅捷薊會短暫地加速周圍的時間流逝，使踐踏者能夠立即執行幾個動作。
plants.swiftthistle.name=迅捷薊
plants.swiftthistle.warden_desc=除了獲得即時行動外，當踐踏迅捷薊時，守衛者還會獲得短暫的加速效果。
