plants.blandfruitbush$seed.name=semente de fruto insípida
plants.blandfruitbush.desc=Prima distante da podridão-da-fruta, a fruta em forma de pera do arbusto de fruta-bland tem um sabor a pó endurecido. A fruta é grosseira e insubstancial, mas não é venenosa. Talvez pudesse ser cozida.
plants.blandfruitbush.discover_hint=Podes encontrar esta planta aleatoriamente na masmorra.
plants.blandfruitbush.name=fruta insípida
plants.blindweed$seed.name=semente de erva-cega
plants.blindweed.desc=Ao ser tocada, a planta-cega perece num clarão intenso. O clarão é suficientemente forte para desorientar durante vários segundos.
plants.blindweed.name=erva-cega
plants.blindweed.warden_desc=_O Guardião_ canalizará a energia de uma erva-cega para um manto temporário de invisibilidade, em vez de ficar desorientado.
plants.earthroot$armor.desc=Espécie de armadura natural e imóvel feita de casca de árvore e corda. Esta armadura de ervas bloqueará o dano de qualquer golpe físico até que a sua durabilidade termine e se desfaça. Como a armadura é imóvel, qualquer movimento fará com que se parta e se perca. Armadura restante:
plants.earthroot$armor.name=armadura de ervas
plants.earthroot$seed.name=semente de raiz da terra
plants.earthroot.desc=Quando uma criatura toca numa raiz terrestre, as suas raízes criam uma espécie de armadura natural imóvel à sua volta.
plants.earthroot.name=raiz da terra
plants.earthroot.warden_desc=As raízes de uma planta da família Heteropapiaceae vão mover-se com a Guardiã, fornecendo-lhe uma armadura móvel de casca de árvore.
plants.fadeleaf$seed.name=semente de folha desbotada
plants.fadeleaf.desc=Ao tocar numa folha desbotada, qualquer criatura será teletransportada para um local aleatório no nível atual.
plants.fadeleaf.name=fadeleaf
plants.fadeleaf.warden_desc=O efeito de teletransporte da folha desbotada é mais potente para a Guardiã, teletransportando-a de volta para o final do nível anterior da masmorra.
plants.firebloom$seed.name=semente de flor de fogo
plants.firebloom.desc=Quando algo toca numa flor de fogo, explode em chamas.
plants.firebloom.name=flor de fogo
plants.firebloom.warden_desc=Quando ela pisa uma flor de fogo, _a Guardiã_ será brevemente imbuída de chamas em vez de ser ferida.
plants.icecap$seed.name=semente da calota polar
plants.icecap.desc=Ao ser tocada, uma calota polar liberta uma nuvem de pólen congelante. O efeito de congelação é muito mais forte se o ambiente estiver húmido.
plants.icecap.name=calota polar
plants.icecap.warden_desc=Quando ela pisa uma calota de gelo, _a Guardiã_ será brevemente imbuída de gelo em vez de ser ferida.
plants.mageroyal$seed.name=semente de mageroyal
plants.mageroyal.desc=As flores espinhosas do mageroyal contêm uma substância química conhecida pelas suas propriedades neutralizantes. Tudo o que entra em contacto com esta planta é purificado de muitos efeitos negativos.
plants.mageroyal.name=mageroyal
plants.mageroyal.refreshed=Sente-se revigorado.
plants.mageroyal.warden_desc=Para além do efeito neutralizador, o Guardião ficará temporariamente imune a todos os efeitos de área ao pisar mageroyal.
plants.plant$seed$placeholder.name=semente
plants.plant$seed.ac_plant=PLANTA
plants.plant$seed.info=Lance esta semente no local onde pretende que uma planta cresça.
plants.plant$seed.seed_of=semente de %s
plants.plant.discover_hint=Podes encontrar esta planta aleatoriamente na masmorra ou cultivá-la a partir da semente associada.
plants.plant.warden_desc=Esta planta não possui qualquer efeito especial quando utilizada pelo Guarda.
plants.rotberry$seed.discover_hint=Podes encontrar este item durante uma missão específica.
plants.rotberry$seed.name=semente de podridão
plants.rotberry.desc=Os frutos de um arbusto jovem de podridão têm um sabor doce e mortal. Ao longo de alguns anos, este arbusto de podridão transformar-se-á noutro foco de podridão. Quando pisado, um jovem arbusto de podridão liberta uma pequena nuvem de gás tóxico.
plants.rotberry.discover_hint=Podes cultivar esta planta a partir da semente associada durante uma missão específica.
plants.rotberry.name=rotberry
plants.rotberry.warden_desc=Normalmente, um arbusto de podridão produz apenas um pouco de gás quando é pisado, mas a Guardiã é capaz de aproveitar a sua energia para aumentar temporariamente a sua força!
plants.sorrowmoss$seed.name=semente de musgo da tristeza
plants.sorrowmoss.desc=A <i>Schizachyrium scoparium</i> é uma flor (não um musgo) com pétalas afiadas como navalhas, revestidas por um veneno mortal.
plants.sorrowmoss.name=musgo da tristeza
plants.sorrowmoss.warden_desc=Quando ela pisa um musgo da tristeza, _o Guardião_ será brevemente imbuído de toxina em vez de ser ferido.
plants.starflower$seed.name=semente de flor-estrela
plants.starflower.desc=Diz-se que a flor-estrela, uma planta rara, concede poder sagrado a quem a toca.
plants.starflower.name=flor-estrela
plants.starflower.warden_desc=Além de ser abençoada, a Guardiã receberá uma quantidade significativa de recarga para a sua varinha ao pisar uma flor-estrela.
plants.stormvine$seed.name=semente de videira da tempestade
plants.stormvine.desc=A gravidade afeta a planta trepadora de forma peculiar, permitindo que os seus finos tentáculos azuis "flutuem" no ar. Tudo o que está preso na trepadeira é afetado e fica desorientado.
plants.stormvine.name=tempestade
plants.stormvine.warden_desc=A Guardiã é capaz de controlar o efeito gravitacional da trepadeira da tempestade e levitará brevemente ao pisar uma.
plants.sungrass$health.desc=A erva-de-sol possui excelentes propriedades curativas, embora seja muito mais lenta do que uma poção de cura. \n\nAfastar-se da planta irá interromper o efeito de cura. \n\nCura restante: %d.
plants.sungrass$health.name=cura com ervas
plants.sungrass$seed.name=semente de erva-sol
plants.sungrass.desc=A erva-de-sol é conhecida pelas lentas, mas eficazes, propriedades curativas da sua seiva.
plants.sungrass.name=capim-sol
plants.sungrass.warden_desc=A Guardiã pode receber a cura da erva-do-sol pisada mesmo que se afaste dela.
plants.swiftthistle$seed.name=semente de cardo-rápido
plants.swiftthistle$timebubble.desc=Uma pequena bolha de tempo acelerado, permitindo que as ações sejam realizadas instantaneamente. Atacar ou usar magia quebrará este efeito. \n\nTurnos restantes: %s.
plants.swiftthistle$timebubble.name=bolha temporal
plants.swiftthistle.desc=Ao ser espezinhado, o cardo-veloz acelera brevemente o fluxo do tempo à sua volta, permitindo a quem o espezinha realizar diversas ações instantaneamente.
plants.swiftthistle.name=cardo-de-cauda-longa
plants.swiftthistle.warden_desc=Além de ganhar ações instantâneas, o Guardião também receberá um breve aumento de velocidade ao pisar cardo-veloz.
