badges$badge.all_armor_identified.desc=在你的日誌中列出所有盔甲
badges$badge.all_armor_identified.title=裝甲研究員
badges$badge.all_artifacts_identified.desc=在你的日誌中找出所有文物。
badges$badge.all_artifacts_identified.title=文物研究員
badges$badge.all_bags_bought.desc=完全擴展您的庫存
badges$badge.all_bags_bought.title=馱騾
badges$badge.all_items_identified.desc=請找出日記中的所有項目
badges$badge.all_items_identified.title=首席研究員
badges$badge.all_potions_identified.desc=在你的日記中記錄所有藥劑。
badges$badge.all_potions_identified.title=藥劑研究員
badges$badge.all_rare_enemies.desc=在你的日誌中填入十條稀有敵人的圖鑑條目
badges$badge.all_rare_enemies.title=大型獵物獵人
badges$badge.all_rings_identified.desc=在你的日記中找出所有圓環。
badges$badge.all_rings_identified.title=環形研究員
badges$badge.all_scrolls_identified.desc=在你的日記中找出所有捲軸
badges$badge.all_scrolls_identified.title=滾動研究員
badges$badge.all_wands_identified.desc=在你的日記中找出所有魔杖。
badges$badge.all_wands_identified.title=魔杖研究員
badges$badge.all_weapons_identified.desc=在你的日誌中列出所有武器
badges$badge.all_weapons_identified.title=武器研究員
badges$badge.boss_challenge_1.desc=在不讓下水道首領使用蓄力攻擊或在水中回復生命值的情況下將其擊敗。
badges$badge.boss_challenge_1.title=無瑕勝利
badges$badge.boss_challenge_2.desc=在不被任何陷阱或危險擊中的情況下擊敗監獄首領
badges$badge.boss_challenge_2.title=明白了！
badges$badge.boss_challenge_3.desc=當洞穴首領處於超強充能狀態時，不受到攻擊或傷害就將其擊敗。
badges$badge.boss_challenge_3.title=智取
badges$badge.boss_challenge_4.desc=在不使用武器、戒指、魔杖或傷害性法術直接攻擊的情況下擊敗城市首領
badges$badge.boss_challenge_4.title=他面前不允許攜帶武器
badges$badge.boss_challenge_5.desc=在所有惡魔生成器存活且「更強大的首領」挑戰開啟的情況下擊敗最終首領。
badges$badge.boss_challenge_5.title=毀滅戰士
badges$badge.boss_slain_1.desc=擊敗下水道盡頭的 Boss
badges$badge.boss_slain_1.title=史萊姆清潔工
badges$badge.boss_slain_1_all_classes.desc=使用所有英雄職業擊敗第一個首領
badges$badge.boss_slain_1_all_classes.title=多面手
badges$badge.boss_slain_2.desc=擊敗監獄盡頭的 Boss。
badges$badge.boss_slain_2.title=監獄長
badges$badge.boss_slain_3.desc=擊敗洞穴盡頭的首領
badges$badge.boss_slain_3.title=金屬廢料回收商
badges$badge.boss_slain_3_all_subclasses.desc=使用所有英雄子職業擊敗第三個首領
badges$badge.boss_slain_3_all_subclasses.title=萬事通
badges$badge.boss_slain_4.desc=擊敗城市盡頭的 Boss。
badges$badge.boss_slain_4.title=征服者國王
badges$badge.boss_slain_remains.desc=擊敗該首領時，身上攜帶已陣亡於該首領的英雄的標誌性物品
badges$badge.boss_slain_remains.title=嚐嚐復仇的滋味！
badges$badge.catalog_one_equipment.desc=在你的日誌中，為每種類型的設備填寫一條目錄條目。
badges$badge.catalog_one_equipment.title=設備齊全
badges$badge.catalog_potions_scrolls.desc=一次識別所有普通藥水和捲軸
badges$badge.catalog_potions_scrolls.title=庫存充足
badges$badge.champion_1.desc=啟用 1 項或多項挑戰後通關。
badges$badge.champion_1.title=銅牌
badges$badge.champion_2.desc=開啟至少 3 項挑戰後通關。
badges$badge.champion_2.title=銀牌冠軍
badges$badge.champion_3.desc=開啟至少 6 項挑戰後通關遊戲
badges$badge.champion_3.title=金牌冠軍
badges$badge.death_from_all.desc=解鎖所有「死因」徽章
badges$badge.death_from_all.title=又一起令人悲傷的死亡
badges$badge.death_from_enemy_magic.desc=死於敵人的魔法攻擊
badges$badge.death_from_enemy_magic.title=電擊
badges$badge.death_from_falling.desc=因墜落而死
badges$badge.death_from_falling.title=煎餅
badges$badge.death_from_fire.desc=死於火災
badges$badge.death_from_fire.title=燒傷
badges$badge.death_from_friendly_magic.desc=死於你自己的魔法物品
badges$badge.death_from_friendly_magic.title=友軍誤傷
badges$badge.death_from_gas.desc=死於有毒氣體
badges$badge.death_from_gas.title=窒息
badges$badge.death_from_grim_trap.desc=死於殘酷或崩潰的陷阱
badges$badge.death_from_grim_trap.title=致命失誤
badges$badge.death_from_hunger.desc=餓死
badges$badge.death_from_hunger.title=飢餓
badges$badge.death_from_poison.desc=死於中毒
badges$badge.death_from_poison.title=中毒
badges$badge.death_from_sacrifice.desc=在祭祀之火旁死去
badges$badge.death_from_sacrifice.title=值得的犧牲
badges$badge.enemy_hazards.desc=在一局遊戲中，利用地形障礙（陷阱、植物或深淵）擊敗 10 個敵人。
badges$badge.enemy_hazards.title=安全隱患
badges$badge.food_eaten_1.desc=在一局遊戲中吃10次食物
badges$badge.food_eaten_1.title=新手美食家
badges$badge.food_eaten_2.desc=在一局遊戲中吃20次食物
badges$badge.food_eaten_2.title=美食達人
badges$badge.food_eaten_3.desc=在一場遊戲中吃30次食物
badges$badge.food_eaten_3.title=美食專家
badges$badge.food_eaten_4.desc=在一場遊戲中吃40次食物
badges$badge.food_eaten_4.title=美食大師
badges$badge.food_eaten_5.desc=在一場遊戲中吃50次食物
badges$badge.food_eaten_5.title=美食大師
badges$badge.games_played_1.desc=玩10局遊戲或贏1局
badges$badge.games_played_1.title=新手地下城探險家
badges$badge.games_played_2.desc=玩25場遊戲或贏得3場遊戲
badges$badge.games_played_2.title=熟練的地下城探險家
badges$badge.games_played_3.desc=玩 50 場遊戲或贏得 5 場遊戲
badges$badge.games_played_3.title=專家級地下城探險家
badges$badge.games_played_4.desc=玩200場遊戲或贏得10場遊戲
badges$badge.games_played_4.title=地下城探險大師
badges$badge.games_played_5.desc=玩1000場遊戲或贏得25場遊戲
badges$badge.games_played_5.title=大師級地下城探險家
badges$badge.gold_collected_1.desc=在一場遊戲中收集 250 金幣
badges$badge.gold_collected_1.title=新手尋寶獵人
badges$badge.gold_collected_2.desc=在一場遊戲中收集1000金幣
badges$badge.gold_collected_2.title=精通尋寶的獵人
badges$badge.gold_collected_3.desc=在一場遊戲中收集2500金幣
badges$badge.gold_collected_3.title=資深尋寶獵人
badges$badge.gold_collected_4.desc=在一場遊戲中收集7500金幣
badges$badge.gold_collected_4.title=尋寶大師
badges$badge.gold_collected_5.desc=在一場遊戲中收集 15,000 金幣
badges$badge.gold_collected_5.title=尋寶大師
badges$badge.grim_weapon.desc=使用格林武器擊敗敵人
badges$badge.grim_weapon.title=死神
badges$badge.happy_end.desc=將延多護符帶到地面
badges$badge.happy_end.title=圓滿結局
badges$badge.happy_end_remains.desc=將陣亡英雄的標誌性物品帶到地面
badges$badge.happy_end_remains.title=你也做到了！
badges$badge.high_score_1.desc=以 5000 分或更高的分數結束遊戲
badges$badge.high_score_1.title=新手追分者
badges$badge.high_score_2.desc=以25000分或更高的分數結束遊戲
badges$badge.high_score_2.title=精明的得分追逐者
badges$badge.high_score_3.desc=以100,000分或更高的分數結束遊戲
badges$badge.high_score_3.title=專家級得分追逐者
badges$badge.high_score_4.desc=以250,000分或更高的分數結束遊戲
badges$badge.high_score_4.title=得分大師
badges$badge.high_score_5.desc=以 1,000,000 分或更高的分數結束遊戲
badges$badge.high_score_5.title=大師級得分追逐者
badges$badge.item_level_1.desc=獲得一件3級或以上的物品
badges$badge.item_level_1.title=新手附魔師
badges$badge.item_level_2.desc=獲得一件6級或以上的物品
badges$badge.item_level_2.title=熟練附魔師
badges$badge.item_level_3.desc=獲得一件9級或以上的物品
badges$badge.item_level_3.title=專家級附魔師
badges$badge.item_level_4.desc=獲得一件12級或以上的物品
badges$badge.item_level_4.title=魔法大師
badges$badge.item_level_5.desc=獲得一件等級15級或以上的物品
badges$badge.item_level_5.title=大師級附魔師
badges$badge.items_crafted_1.desc=在一場遊戲中透過煉金術製作 3 件物品
badges$badge.items_crafted_1.title=新手煉金術士
badges$badge.items_crafted_2.desc=在一場遊戲中透過煉金術製作 8 件物品
badges$badge.items_crafted_2.title=精通煉金術的煉金術士
badges$badge.items_crafted_3.desc=在一場遊戲中透過煉金術製作 15 件物品
badges$badge.items_crafted_3.title=煉金術專家
badges$badge.items_crafted_4.desc=在一場遊戲中透過煉金術製作 24 件物品
badges$badge.items_crafted_4.title=煉金術大師
badges$badge.items_crafted_5.desc=在一場遊戲中透過煉金術製作 35 件物品
badges$badge.items_crafted_5.title=煉金術大師
badges$badge.level_reached_1.desc=達到6級
badges$badge.level_reached_1.title=新手冒險者
badges$badge.level_reached_2.desc=達到12級
badges$badge.level_reached_2.title=精通冒險的
badges$badge.level_reached_3.desc=達到18級
badges$badge.level_reached_3.title=專家級冒險家
badges$badge.level_reached_4.desc=達到24級
badges$badge.level_reached_4.title=冒險大師
badges$badge.level_reached_5.desc=達到30級
badges$badge.level_reached_5.title=冒險大師
badges$badge.many_buffs.desc=同時啟動10個或更多增益/減益圖示。
badges$badge.many_buffs.title=如此多的顏色
badges$badge.mastery_combo.desc=達到10連擊
badges$badge.mastery_combo.title=角鬥士之怒
badges$badge.monsters_slain_1.desc=在一場遊戲中擊敗 10 個敵人
badges$badge.monsters_slain_1.title=新手魔物獵人
badges$badge.monsters_slain_2.desc=在一場遊戲中擊敗 50 個敵人
badges$badge.monsters_slain_2.title=熟練的怪物獵人
badges$badge.monsters_slain_3.desc=在一場遊戲中擊敗 100 個敵人
badges$badge.monsters_slain_3.title=專家級魔物獵人
badges$badge.monsters_slain_4.desc=在一場遊戲中擊敗 250 個敵人
badges$badge.monsters_slain_4.title=大師級怪物獵人
badges$badge.monsters_slain_5.desc=在一場遊戲中擊敗 500 個敵人
badges$badge.monsters_slain_5.title=大師級怪物獵人
badges$badge.no_monsters_slain.desc=不擊敗任何敵人就完成一層
badges$badge.no_monsters_slain.title=和平主義者
badges$badge.pacifist_ascent.desc=將延多護符帶到地面，但不要減輕其詛咒的嚴重程度。
badges$badge.pacifist_ascent.title=和平主義者的崛起
badges$badge.piranhas.desc=在一場遊戲中殺死 6 條食人魚
badges$badge.piranhas.title=非傳統釣客
badges$badge.researcher_1.desc=在你的日誌中填寫 40 個目錄條目
badges$badge.researcher_1.title=新手研究員
badges$badge.researcher_2.desc=在你的日誌中填寫 80 個目錄條目
badges$badge.researcher_2.title=熟練的研究員
badges$badge.researcher_3.desc=在你的日誌中填寫160個目錄條目
badges$badge.researcher_3.title=專家研究員
badges$badge.researcher_4.desc=在你的日誌中填寫 320 個目錄條目
badges$badge.researcher_4.title=首席研究員
badges$badge.researcher_5.desc=在你的日誌中填寫每一個目錄條目。
badges$badge.researcher_5.title=特級研究員
badges$badge.rodney.desc=找出矮人王的真名
badges$badge.rodney.title=現在沒那麼嚇人了。
badges$badge.strength_attained_1.desc=達到12點基礎力量值
badges$badge.strength_attained_1.title=新手健美運動員
badges$badge.strength_attained_2.desc=達到14點基礎力量值
badges$badge.strength_attained_2.title=健美高手
badges$badge.strength_attained_3.desc=達到16點基礎力量值
badges$badge.strength_attained_3.title=專業健美運動員
badges$badge.strength_attained_4.desc=達到18點基礎力量值
badges$badge.strength_attained_4.title=健美大師
badges$badge.strength_attained_5.desc=達到20點基礎力量值
badges$badge.strength_attained_5.title=健美大師
badges$badge.taking_the_mick.desc=用+20或更高的鎬子給予最終頭目致命一擊。
badges$badge.taking_the_mick.title=開玩笑
badges$badge.unlock_cleric.desc=徹底清除任何一件詛咒裝備上的詛咒，即可解鎖牧師職業。
badges$badge.unlock_cleric.title=牧師解鎖！
badges$badge.unlock_duelist.desc=裝備一把無力量懲罰的2級或更高階武器即可解鎖決鬥者職業
badges$badge.unlock_duelist.title=決鬥者解鎖！
badges$badge.unlock_huntress.desc=在一局遊戲中用投擲武器擊中敵人 10 次即可解鎖女獵手
badges$badge.unlock_huntress.title=女獵手解鎖！
badges$badge.unlock_mage.desc=使用升級捲軸解鎖法師
badges$badge.unlock_mage.title=法師解鎖！
badges$badge.unlock_rogue.desc=在一場遊戲中完成 10 次突襲即可解鎖「盜賊」角色
badges$badge.unlock_rogue.title=叛逆者解鎖！
badges$badge.victory.desc=獲得延多護符
badges$badge.victory.title=勝利！
badges$badge.victory_all_classes.desc=使用每個英雄職業獲得延多護符
badges$badge.victory_all_classes.title=精通多種技藝
badges$badge.victory_random.desc=取得延多護符，隨機選擇英雄、天賦升級、副職業和護甲技能。
badges$badge.victory_random.title=隨機勝利！
badges$badge.ring_of_haggler.desc=讓討價還價者之環為人所知/被識別。
badges$badge.ring_of_haggler.title=討價還價者之戒
badges$badge.ring_of_thorns.desc=讓世人知道/認出荊棘之環。
badges$badge.ring_of_thorns.title=荊棘之戒
badges$badge.supporter.desc=透過捐款、帳單或商店權益，實現支持者的所有權/解鎖。
badges$badge.supporter.title=感謝您的支持！
badges$badge.yasd.desc=在遊戲過程中解鎖火焰、毒素、毒氣和飢餓死亡徽章。
badges$badge.yasd.title=死於火災、中毒、毒氣和飢餓
badges$badge.rare.desc=至少擊殺以下每種稀有怪物變種一次：白化怪、強盜怪、帶盾怪、老怪和酸怪。
badges$badge.rare.title=所有稀有怪物都已擊殺
badges$badge.champion.desc=在至少一項挑戰啟用的情況下贏得比賽。
badges$badge.champion.title=挑戰成功
badges$badge.potions_cooked_1.desc=一次遊戲中至少製作 3 瓶藥水。
badges$badge.potions_cooked_1.title=3瓶熬製好的藥劑
badges$badge.potions_cooked_2.desc=一次遊戲中至少製作 6 瓶藥水。
badges$badge.potions_cooked_2.title=熬製了6瓶藥劑
badges$badge.potions_cooked_3.desc=一次遊戲中至少製作 9 瓶藥劑。
badges$badge.potions_cooked_3.title=熬製了9瓶藥劑
badges$badge.potions_cooked_4.desc=一次遊戲中至少製作 12 瓶藥水。
badges$badge.potions_cooked_4.title=熬製了12瓶藥劑
badges$badge.death_from_glyph.desc=死於魔法或符文效果。
badges$badge.death_from_glyph.title=死於魔法
badges$badge.night_hunter.desc=夜間擊殺15隻怪物。
badges$badge.night_hunter.title=夜間擊殺15隻怪物
badges.endorsed=徽章認證號：%s。
badges.new=徽章解鎖：%s。
challenges.champion_enemies=敵對冠軍
challenges.champion_enemies_desc=你不是唯一可以升級的人！普通敵人有 1/8 的幾率在第一層生成時帶有特殊冠軍增益效果，到第二十一層時幾率提升至 1/6。冠軍如果生成時處於睡眠狀態，則會醒來。英雄會知道何時生成了冠軍。冠軍無法轉化為盟友。冠軍敵人有六種類型：熾焰（橘色）：+25% 近戰傷害，擊中時點燃，死亡時散播火焰，無法點燃水格。投射（紫色）：+25% 近戰傷害，+3 近戰範圍。反魔法（綠色）： -50%受到的傷害，免疫魔法效果\n_巨人（藍色）：-80%受到的傷害，+1近戰範圍，無法進入隧道\n_祝福（黃色）：4倍命中率和閃避率\n_ZXQ_祝福（黃色）：4倍命中率和閃避率\n_（紅色）：+20%。每4回合增加1%。
challenges.darkness=陷入黑暗
challenges.darkness_desc=畢竟這是地牢！ \n\n- 常規可視距離大幅縮短\n- 每層都會出現一個火炬\n- 其他光源的效率降低至原來的五分之一
challenges.no_armor=信仰是我的盔甲
challenges.no_armor_desc=你需要對自己有信心，因為你的盔甲作用不大！ \n\n- 除布甲外，所有盔甲的基礎格擋能力降低\n- 所有盔甲升級後獲得的格擋能力提升都非常小\n- 大地守護者的防禦能力也大幅降低
challenges.no_food=節食
challenges.no_food_desc=食物本來就稀缺，但你得注意份量！食物和豐饒之角飽足的效果只有原來的三分之一。其他飽足來源不受影響。
challenges.no_healing=藥物恐懼症
challenges.no_healing_desc=治療藥水確實很方便，可惜你對它們過敏！ \n\n- 治療藥水、配方中使用治療藥水的物品以及太陽果會使英雄中毒而不是治療他們。 \n- 不穩定的藥劑不會隨機使英雄中毒或治療。 \n- 這些物品對其他角色仍然有效。
challenges.no_herbalism=不毛之地
challenges.no_herbalism_desc=這該死的地牢裡似乎已經沒有乾淨的水了…\n\n- 露珠已被移除\n- 植物已被移除\n- 種子仍然出現，但不會發芽
challenges.no_scrolls=禁忌符文
challenges.no_scrolls_desc=某個符文更難找到。不幸的是，它總是最有用的。地牢中一半的升級捲軸被移除。
challenges.stronger_bosses=更糟的老闆
challenges.stronger_bosses_desc=這次挑戰中，Boss 戰難度大幅提升！ \n\n_Goo：生命值 +20%\n_-_水中治療量提升至每回合 3 次\n_-_充氣時間縮短至 1 回合而非 2 回合\n_Tengu：生命值+25%\n_-_第一階段：陷阱威力大幅提升\n_-_第二階段：技能觸發頻率更高\n_DM-300：生命值 +33%\n_-_能量塔更堅固，且可啟動 3個\n_-_技能威力更強，觸發頻率更高\n_-_DM-300充能後速度更快\n_-_裸露的電線出現頻率翻倍\n_矮人王：生命值+50%\n_-_所有階段小兵更強\n_-_第一階段：技能和召喚速度更快\n_-_第二階段：每回合多召喚2個小兵\n_-_第三階段：生命值翻倍，召喚速度更快\n_尤格-澤瓦：\n_-_一次召喚兩個拳頭！ \n_-_雷射傷害+60%\n_-_更強的小兵
challenges.swarm_intelligence=群體智能
challenges.swarm_intelligence_desc=小心，地牢怪物越來越聰明了！當敵人發現你時，附近的敵人會被吸引到那個位置。
rankings$record.ascended=借助護身符升天！
rankings$record.something=被某種東西殺死
rankings$record.won=獲得了延多護符
