ui.customnotebutton$customnotewindow.add_text=新增文字
ui.customnotebutton$customnotewindow.cancel=取消
ui.customnotebutton$customnotewindow.confirm=確認
ui.customnotebutton$customnotewindow.delete=刪除
ui.customnotebutton$customnotewindow.delete_warn=您確定要刪除此自訂備註嗎？
ui.customnotebutton$customnotewindow.edit_text=編輯文字
ui.customnotebutton$customnotewindow.edit_title=編輯標題
ui.customnotebutton.desc=自訂筆記允許你在日誌中記錄任何你想記錄的內容。它們可以是單獨的文本，也可以與地牢樓層、你的物品或藥水/捲軸/戒指類型相關聯。
ui.customnotebutton.limit_text=您可以刪除現有筆記以騰出空間添加更多筆記。所有您目前的自訂筆記都可以在日記視窗中查看。
ui.customnotebutton.limit_title=已達限額
ui.customnotebutton.new_floor=新地牢樓層提示
ui.customnotebutton.new_floor_prompt=選擇地牢的某一層來關聯這張紙條。
ui.customnotebutton.new_floor_title=請為樓層 %d 的這條自訂備註寫一個標題：
ui.customnotebutton.new_inv=新庫存物品說明
ui.customnotebutton.new_inv_prompt=選擇備註項
ui.customnotebutton.new_item_title=請為項目 \n_%s_ 的自訂備註填寫標題
ui.customnotebutton.new_text=新文字註釋
ui.customnotebutton.new_text_title=請為此自訂文字筆記填寫標題：
ui.customnotebutton.new_type=新項目類型說明
ui.customnotebutton.new_type_prompt=請選擇您希望將此便箋關聯的物品類型。
ui.customnotebutton.title=新增自訂備註
ui.quickslotbutton.select_item=快捷欄物品
ui.talentspane.random_no=我稍後再決定。
ui.talentspane.random_one=隨便花一個。
ui.talentspane.random_sure=你確定要隨意使用這些天賦點數嗎？
ui.talentspane.random_title=隨機天賦
ui.talentspane.random_yes=是的，全部花掉。
ui.talentspane.tier=層 %d
ui.talentspane.unlock_tier2=達到6級即可解鎖更多天賦。
ui.talentspane.unlock_tier3=達到 12 級並使用第二個 Boss 掉落的物品來解鎖更多天賦。
ui.talentspane.unlock_tier4=達到 20 級並使用第四個 Boss 掉落的物品來解鎖更多天賦。
ui.toolbar.container_cancel=取消
ui.toolbar.container_empty=那個容器是空的！
ui.toolbar.container_prompt=選擇一個容器
ui.toolbar.container_select=選擇容器
ui.toolbar.examine_prompt=再次按下以搜尋\n按下圖塊進行檢查
ui.toolbar.item_cancel=取消
ui.toolbar.item_prompt=選擇一個項目
ui.toolbar.item_select=選擇項目
ui.toolbar.item_use=快速使用物品
ui.toolbar.quickslot_assign=指派快速欄位
ui.toolbar.quickslot_cancel=取消
ui.toolbar.quickslot_prompt=選擇一個快速欄位
ui.toolbar.quickslot_select=選擇快速欄
ui.updatenotification$wndupdate.button=前往更新頁面
ui.updatenotification$wndupdate.title=有更新可用！
ui.updatenotification$wndupdate.versioned_title=可用更新：%s
ui.updatenotification.title=更新
