scenes.alchemyscene.add=新增項目
scenes.alchemyscene.cancel=取消成分
scenes.alchemyscene.craft=工藝
scenes.alchemyscene.energize=啟動物品
scenes.alchemyscene.energy=活力：
scenes.alchemyscene.guide=指導
scenes.alchemyscene.no_items=那個袋子裡沒有可以煉金的物品。
scenes.alchemyscene.repeat=重複成分
scenes.alchemyscene.select=選擇一個項目
scenes.alchemyscene.text=將各種食材組合起來，創造出新的美味！
scenes.alchemyscene.title=煉金術
scenes.amuletscene.exit=今天就到此為止吧。
scenes.amuletscene.stay=我還沒完成。
scenes.amuletscene.text=你終於將它握在手中－延多護符！有了這護符的力量，沒有什麼能阻擋你！你征服了地牢，完成了你的使命！或者，也許你還沒準備好？你也可以選擇暫時保留護符，繼續當個凡人，或許可以用最原始的方式離開地牢…
scenes.changesscene.buffs=巴夫斯
scenes.changesscene.bugfixes=錯誤修復
scenes.changesscene.changes=變化
scenes.changesscene.lang_warn=變更詳情由開發者編寫，僅提供英文版本。
scenes.changesscene.language=語言改進
scenes.changesscene.misc=其他變更
scenes.changesscene.nerfs=削弱
scenes.changesscene.new=新內容
scenes.changesscene.right_body=選擇左側的圖標，即可查看該次更新所帶來的變更。
scenes.changesscene.right_title=更改詳情
scenes.changesscene.title=更改歷史記錄
scenes.gamescene.attack=攻擊
scenes.gamescene.choose_examine=選擇“檢查”
scenes.gamescene.descend=你下到地牢的第 %d 層。
scenes.gamescene.dont_know=你不知道那裡有什麼。
scenes.gamescene.examine=檢查
scenes.gamescene.go_here=點擊此處
scenes.gamescene.interact=相互影響
scenes.gamescene.multiple=多個物件
scenes.gamescene.multiple_examine=這裡有很多值得關注的地方，你想研究哪一個？
scenes.gamescene.pick_up=撿起
scenes.gamescene.purchase=購買
scenes.gamescene.resurrect=你出現在 %d 樓層的某個位置。
scenes.gamescene.return=你返回到地牢的第 %d 層。
scenes.gamescene.secret_hint=你確信這層樓的某個地方藏著一個密室。
scenes.gamescene.spawner_warn=你感覺頭頂上方有一股邪惡的能量源…
scenes.gamescene.spawner_warn_final=你能感覺到從上一層樓散發出來的邪惡氣息！
scenes.gamescene.trample=踐踏
scenes.gamescene.tutorial_guidebook_desktop=選擇右上角閃爍的日記按鈕（%s）來閱讀你剛拿起的書。
scenes.gamescene.tutorial_guidebook_mobile=點擊右上角閃爍的日記按鈕，即可閱讀你剛拿起的書籍。
scenes.gamescene.tutorial_move_controller=選擇位置或使用左搖桿移動或互動。
scenes.gamescene.tutorial_move_desktop=使用滑鼠、WASD 鍵或方向鍵進行移動和互動。
scenes.gamescene.tutorial_move_mobile=點擊位置即可移動和互動。
scenes.gamescene.tutorial_ui_desktop=英雄訊息（%1$s）在下方。物品欄（%2$s）、快速欄和遊戲操作在右側。祝你好運！
scenes.gamescene.tutorial_ui_mobile=英雄訊息位於左上角。物品欄、快捷欄和遊戲操作位於下方。祝你好運！
scenes.gamescene.warp=你周圍的牆壁會扭曲變形！
scenes.heroselectscene.challenges_nowin=挑戰是可選的難度調整項，可以增加遊戲難度。有些挑戰會增加地牢的危險性，有些則會降低你的技能或物品的威力。你必須至少贏得一局遊戲才能啟用挑戰。
scenes.heroselectscene.custom_seed=客製化種子
scenes.heroselectscene.custom_seed_clear=清除
scenes.heroselectscene.custom_seed_desc=遊戲使用種子碼生成地下城，相同的種子碼和遊戲版本總是生成相同的地下城！ _自訂種子遊戲無法獲得徽章或計入遊戲次數，並且會顯示在排行榜頁面的底部。 _
scenes.heroselectscene.custom_seed_duplicate=您目前已使用該種子進行一局常規遊戲。您必須先結束該遊戲，才能使用該自訂種子。
scenes.heroselectscene.custom_seed_nowin=遊戲使用種子碼生成地下城，相同的種子碼和遊戲版本總是生成相同的地下城！ \n\n_您必須至少贏得一局遊戲才能輸入自訂種子。 _
scenes.heroselectscene.custom_seed_set=放
scenes.heroselectscene.custom_seed_title=輸入自訂種子
scenes.heroselectscene.daily=每日跑步
scenes.heroselectscene.daily_desc=每天都會推出一款全新的遊戲，所有玩家都能體驗到相同的內容！這個「每日挑戰」會為每位玩家生成相同的地下城（前提是他們玩的是同一遊戲版本）。您可以隨意安排完成每日挑戰的時間，但一次只能進行一次。每日挑戰不參與徽章獎勵，並擁有獨立的排名頁面。您想使用當前選擇的英雄和挑戰開始今天的每日挑戰嗎？
scenes.heroselectscene.daily_existing=您目前已有一個每日跑步任務正在進行中。您必須先結束目前的跑步任務，才能開始另一個每日跑步任務。
scenes.heroselectscene.daily_no=不
scenes.heroselectscene.daily_nowin=每天都會推出一款全新的遊戲，而且所有玩家的遊戲內容都相同！這個「每日挑戰」會為每位玩家生成相同的地下城（前提是他們玩的是同一遊戲版本）。您必須至少贏得一場遊戲才能參與每日挑戰。
scenes.heroselectscene.daily_repeat=您已完成今天的每日挑戰。您可以重玩，但僅限非排名練習。重玩結束後，您可以在每日排名視窗中查看記錄一段時間，之後記錄將會被刪除。您想使用當前選擇的英雄和挑戰重玩今天的每日挑戰嗎？
scenes.heroselectscene.daily_unavailable_long=您似乎開啟了一個未來的每日挑戰！如果您最近更改了時區或系統時鐘，就可能發生這種情況。您的下一個每日挑戰將在 %d 天後發布。
scenes.heroselectscene.daily_yes=是的
scenes.heroselectscene.options=遊戲選項
scenes.heroselectscene.randomize=隨機化
scenes.heroselectscene.randomize_cancel=取消
scenes.heroselectscene.randomize_chals=隨機挑戰
scenes.heroselectscene.randomize_chals_title=挑戰
scenes.heroselectscene.randomize_confirm=確認
scenes.heroselectscene.randomize_hero=隨機英雄
scenes.heroselectscene.start=開始
scenes.heroselectscene.title=選擇你的英雄
scenes.interlevelscene$mode.ascend=上升
scenes.interlevelscene$mode.continue=載入中
scenes.interlevelscene$mode.descend=下降
scenes.interlevelscene$mode.fall=墜落！
scenes.interlevelscene$mode.reset=重置
scenes.interlevelscene$mode.resurrect=復活
scenes.interlevelscene$mode.return=返回
scenes.interlevelscene.continue=繼續
scenes.interlevelscene.file_not_found=未找到存檔檔。如果重新啟動後此錯誤仍然存在，則可能表示此存檔已損壞。對此我們深表歉意。
scenes.interlevelscene.io_error=無法讀取存檔檔案。如果重新啟動後此錯誤仍然存在，則可能表示此存檔已損壞。對此我們深表歉意。
scenes.journalscene.title=雜誌
scenes.newsscene$newsinfo.enable_data=檢查行動數據
scenes.newsscene$newsinfo.enable_news=啟用新聞
scenes.newsscene$newsinfo.english_warn=新聞文章由開發者撰寫，僅提供英文版本。
scenes.newsscene$newsinfo.metered_network=由於您連接的是按流量計費的網路（例如行動數據），因此無法查看新聞貼文。
scenes.newsscene$newsinfo.news_disabled=您已停用新聞貼文檢查，因此此處不會顯示任何新聞貼文。
scenes.newsscene$newsinfo.no_internet=無法查看新聞帖子，請確保您已連接到互聯網。
scenes.newsscene.read_more=閱讀更多
scenes.newsscene.title=遊戲新聞
scenes.rankingsscene.no_games=目前還沒有進行任何比賽。
scenes.rankingsscene.no_info=沒有其他資訊
scenes.rankingsscene.title=排名
scenes.rankingsscene.total=已進行遊戲場次：
scenes.startscene.days_ago=%d 天前
scenes.startscene.hours_ago=%d 小時前
scenes.startscene.minutes_ago=%d 分鐘前
scenes.startscene.months_ago=%d 幾個月前
scenes.startscene.new=新遊戲
scenes.startscene.one_minute_ago=1分鐘前
scenes.startscene.sort_level=排序：級別
scenes.startscene.sort_recent=排序：最新
scenes.startscene.title=進行中的遊戲
scenes.supporterscene.patreon_english=（請注意，Patreon獎勵目前僅提供英文版本。）
scenes.supporterscene.supporter_link=前往 Patreon 頁面
scenes.supporterscene.title=支援遊戲
scenes.surfacescene.exit=遊戲結束
scenes.titlescene$changesbutton.changes=目前更改螢幕
scenes.titlescene$changesbutton.title=有更新可用！
scenes.titlescene$changesbutton.update=前往更新頁面
scenes.titlescene$changesbutton.versioned_title=可用更新：%s
scenes.titlescene.about=關於
scenes.titlescene.changes=變化
scenes.titlescene.enter=進入地牢
scenes.titlescene.install=安裝
scenes.titlescene.journal=雜誌
scenes.titlescene.news=訊息
scenes.titlescene.patreon_button=Patreon頁面
scenes.titlescene.play=玩
scenes.titlescene.rankings=排名
scenes.titlescene.settings=設定
scenes.titlescene.support=支援遊戲
scenes.titlescene.update=更新
scenes.welcomescene.changelist=變更列表
scenes.welcomescene.continue=繼續
scenes.welcomescene.controller_body=使用手把玩遊戲？使用右搖桿控制螢幕上的遊標。按 RT/R2 或右搖桿即可使用遊標進行選擇。
scenes.welcomescene.controller_okay=好的
scenes.welcomescene.controller_title=控制器輸入
scenes.welcomescene.lang_warning_msg=本次更新的部分新內容尚未翻譯。部分短語可能仍為英文。翻譯團隊正在努力解決此問題，完整翻譯版本將很快發布。感謝您的耐心等待。
scenes.welcomescene.lang_warning_title=不完整翻譯
scenes.welcomescene.patch_balance=此補丁包含對遊戲平衡性的調整。
scenes.welcomescene.patch_bugfixes=此補丁包含錯誤修復。
scenes.welcomescene.patch_msg=此補丁還包含一些小的調整和效能改進。
scenes.welcomescene.patch_translations=此補丁包含翻譯更新。
scenes.welcomescene.update_msg=v3.3 版本包含一個用於測試即將進行的城市任務大改版的區域、新物品以及一系列較小的調整和改進。
