scenes.alchemyscene.add=Adicionar item
scenes.alchemyscene.cancel=Cancelar ingredientes
scenes.alchemyscene.craft=Ofício
scenes.alchemyscene.energize=Itens energizantes
scenes.alchemyscene.energy=Energia:
scenes.alchemyscene.guide=Guia
scenes.alchemyscene.no_items=Não há itens alquimizáveis nesta bolsa.
scenes.alchemyscene.repeat=Repita os ingredientes
scenes.alchemyscene.select=Selecione um item
scenes.alchemyscene.text=Combine ingredientes para criar algo novo!
scenes.alchemyscene.title=Alquimia
scenes.amuletscene.exit=Vamos terminar por hoje.
scenes.amuletscene.stay=Eu ainda não terminei.
scenes.amuletscene.text=Finalmente, tem-no nas suas mãos: o Amuleto de Yendor! Com o poder deste amuleto, nada o poderá deter! Conquistaste a masmorra e completaste a tua missão! Ou talvez ainda não esteja pronto? Também pode decidir simplesmente guardar o amuleto, permanecer como um mero mortal por mais algum tempo e, quem sabe, abandonar a masmorra da forma tradicional...
scenes.changesscene.buffs=Buffs
scenes.changesscene.bugfixes=Correções de bugs
scenes.changesscene.changes=Mudanças
scenes.changesscene.lang_warn=Os detalhes das alterações são escritos pelo programador e estão disponíveis apenas em inglês.
scenes.changesscene.language=Aprimoramentos de linguagem
scenes.changesscene.misc=Alterações diversas
scenes.changesscene.nerfs=Nerfs
scenes.changesscene.new=Novo conteúdo
scenes.changesscene.right_body=Selecione um ícone à esquerda para ler sobre as alterações dessa atualização.
scenes.changesscene.right_title=Alterar detalhes
scenes.changesscene.title=Histórico de alterações
scenes.gamescene.attack=Ataque
scenes.gamescene.choose_examine=Selecione Examinar
scenes.gamescene.descend=Desce-se até ao andar %d da masmorra.
scenes.gamescene.dont_know=Não sabe o que há lá.
scenes.gamescene.examine=Examinar
scenes.gamescene.go_here=Acesse aqui
scenes.gamescene.interact=Interagir
scenes.gamescene.multiple=Vários objetos
scenes.gamescene.multiple_examine=Há aqui vários aspetos interessantes. Qual deles gostaria de examinar?
scenes.gamescene.pick_up=Levantar
scenes.gamescene.purchase=Compra
scenes.gamescene.resurrect=Materializas-te algures no andar %d.
scenes.gamescene.return=Regressas ao andar %d da masmorra.
scenes.gamescene.secret_hint=Tens a certeza de que existe uma sala secreta algures neste piso.
scenes.gamescene.spawner_warn=Sente que existe uma fonte de energia demoníaca acima de si...
scenes.gamescene.spawner_warn_final=É possível sentir a energia demoníaca a emanar dos pisos anteriores!
scenes.gamescene.trample=Pisotear
scenes.gamescene.tutorial_guidebook_desktop=Seleciona o botão do diário intermitente (%s) no canto superior direito para leres o livro que acabaste de apanhar.
scenes.gamescene.tutorial_guidebook_mobile=Toca no botão do diário intermitente no canto superior direito para ler o livro que acabaste de apanhar.
scenes.gamescene.tutorial_move_controller=Selecione um local ou utilize o joystick esquerdo para se mover ou interagir.
scenes.gamescene.tutorial_move_desktop=Utiliza o rato, as teclas WASD ou as setas do teclado para te movimentares e interagires.
scenes.gamescene.tutorial_move_mobile=Toque num local para se mover e interagir.
scenes.gamescene.tutorial_ui_desktop=As informações do herói (%1$s) estão abaixo. O inventário (%2$s), os atalhos e as ações do jogo estão à direita. Boa sorte!
scenes.gamescene.tutorial_ui_mobile=As informações do herói estão no canto superior esquerdo. O inventário, os atalhos e as ações de jogo estão abaixo. Boa sorte!
scenes.gamescene.warp=As paredes deformam-se e movem-se ao seu redor!
scenes.heroselectscene.challenges_nowin=Os desafios são modificadores opcionais que tornam o jogo mais difícil. Alguns desafios tornam a masmorra mais perigosa, outros reduzem o poder das suas habilidades ou itens. Precisas de vencer pelo menos uma partida antes de poderes ativar os desafios.
scenes.heroselectscene.custom_seed=Sementes personalizadas
scenes.heroselectscene.custom_seed_clear=Claro
scenes.heroselectscene.custom_seed_desc=O jogo utiliza um código de semente para a geração de masmorras; a mesma semente e versão do jogo geram sempre a mesma masmorra! _Os jogos com sementes personalizadas não podem ganhar crachás nem contribuir para o número de jogos jogados e aparecem na parte inferior da página de classificação. _
scenes.heroselectscene.custom_seed_duplicate=Já tens um jogo normal em andamento com essa seed. Precisas de terminar esse jogo antes de usar a seed personalizada.
scenes.heroselectscene.custom_seed_nowin=O jogo utiliza um código de semente para a geração de masmorras; a mesma semente e versão do jogo geram sempre a mesma masmorra! \n\n_Precisa de vencer pelo menos uma partida antes de poder inserir sementes personalizadas._
scenes.heroselectscene.custom_seed_set=CONJUNTO
scenes.heroselectscene.custom_seed_title=Insira uma semente personalizada
scenes.heroselectscene.daily=Corrida diária
scenes.heroselectscene.daily_desc=Todos os dias, é disponibilizado um novo jogo, sendo o mesmo para todos! Esta "corrida diária" gera a mesma masmorra para todos os que a jogam (desde que estejam a jogar a mesma versão do jogo). Pode demorar o tempo que quiser para completar uma corrida diária, mas só pode ter uma ativa de cada vez. As corridas diárias não são elegíveis para emblemas e têm a sua própria página de classificação. Gostaria de começar a corrida diária de hoje com o herói e os desafios que selecionou?
scenes.heroselectscene.daily_existing=Já tem uma corrida diária em andamento. Precisa de encerrar essa corrida antes de iniciar outra.
scenes.heroselectscene.daily_no=Não
scenes.heroselectscene.daily_nowin=Todos os dias, é disponibilizado um novo jogo, sendo o mesmo para todos! Esta "partida diária" gera a mesma masmorra para todos os jogadores (desde que estejam a jogar a mesma versão do jogo). Precisa de vencer pelo menos uma partida para poder participar nas partidas diárias.
scenes.heroselectscene.daily_repeat=Já jogou a missão diária de hoje. Pode jogá-la novamente, se quiser, mas apenas como uma partida de treino sem classificação. Após concluir a repetição, poderá visualizá-la na janela de classificação diária durante um curto período antes de o registo ser eliminado. Deseja jogar novamente a missão diária de hoje com o herói e os desafios que selecionou?
scenes.heroselectscene.daily_unavailable_long=Parece que iniciou uma atualização diária que está no futuro! Isto pode acontecer se tiver mudado de fuso horário recentemente ou se tiver alterado o relógio do sistema. _A sua próxima atualização diária estará disponível daqui a %d dias._
scenes.heroselectscene.daily_yes=Sim
scenes.heroselectscene.options=Opções do jogo
scenes.heroselectscene.randomize=Aleatorizar
scenes.heroselectscene.randomize_cancel=Cancelar
scenes.heroselectscene.randomize_chals=Desafios Randomizados
scenes.heroselectscene.randomize_chals_title=Desafios
scenes.heroselectscene.randomize_confirm=Confirmar
scenes.heroselectscene.randomize_hero=Herói aleatório
scenes.heroselectscene.start=Iniciar
scenes.heroselectscene.title=Escolha o seu herói
scenes.interlevelscene$mode.ascend=Ascendente
scenes.interlevelscene$mode.continue=Carregando
scenes.interlevelscene$mode.descend=Descendente
scenes.interlevelscene$mode.fall=Caindo!
scenes.interlevelscene$mode.reset=Reiniciando
scenes.interlevelscene$mode.resurrect=Ressuscitando
scenes.interlevelscene$mode.return=Retornando
scenes.interlevelscene.continue=Continuar
scenes.interlevelscene.file_not_found=Ficheiro de salvamento não encontrado. Se este erro persistir após reiniciar, pode significar que o ficheiro de gravação está corrompido. Pedimos desculpa pelo inconveniente.
scenes.interlevelscene.io_error=Não foi possível ler o ficheiro de gravação. Se este erro persistir após reiniciar, pode significar que o ficheiro de gravação está corrompido. Pedimos desculpa pelo inconveniente.
scenes.journalscene.title=Jornal
scenes.newsscene$newsinfo.enable_data=Verificar dados móveis
scenes.newsscene$newsinfo.enable_news=Ativar notícias
scenes.newsscene$newsinfo.english_warn=As notícias são escritas pelo programador e estão disponíveis apenas em inglês.
scenes.newsscene$newsinfo.metered_network=Não foi possível verificar se existem publicações noticiosas, uma vez que está ligado a uma rede com limite de dados, como dados móveis.
scenes.newsscene$newsinfo.news_disabled=Desativou a verificação de novas publicações, pelo que nenhuma aparecerá aqui.
scenes.newsscene$newsinfo.no_internet=Não foi possível verificar se existem publicações noticiosas. Certifique-se de que está ligado à internet.
scenes.newsscene.read_more=Leia mais
scenes.newsscene.title=Notícias de jogos
scenes.rankingsscene.no_games=Nenhuma partida foi disputada ainda.
scenes.rankingsscene.no_info=Nenhuma informação adicional
scenes.rankingsscene.title=Classificações
scenes.rankingsscene.total=Jogos jogados:
scenes.startscene.days_ago=%d há dias
scenes.startscene.hours_ago=%d há horas
scenes.startscene.minutes_ago=%d há minutos
scenes.startscene.months_ago=%d há meses
scenes.startscene.new=Novo jogo
scenes.startscene.one_minute_ago=Há 1 minuto
scenes.startscene.sort_level=Ordenar por: Nível
scenes.startscene.sort_recent=Ordenar por: Mais recentes
scenes.startscene.title=Jogos em curso
scenes.supporterscene.patreon_english=(Note que as recompensas do Patreon só estão disponíveis em inglês.)
scenes.supporterscene.supporter_link=Aceda à página do Patreon.
scenes.supporterscene.title=Apoie o jogo
scenes.surfacescene.exit=Game Over
scenes.titlescene$changesbutton.changes=Ecrã de alterações atuais
scenes.titlescene$changesbutton.title=Uma atualização está disponível!
scenes.titlescene$changesbutton.update=Aceda à página de atualização.
scenes.titlescene$changesbutton.versioned_title=Atualização disponível: %s
scenes.titlescene.about=Sobre
scenes.titlescene.changes=Mudanças
scenes.titlescene.enter=Entre na masmorra
scenes.titlescene.install=Instalar
scenes.titlescene.journal=Jornal
scenes.titlescene.news=Notícias
scenes.titlescene.patreon_button=Página do Patreon
scenes.titlescene.play=Brincadeira
scenes.titlescene.rankings=Classificações
scenes.titlescene.settings=Configurações
scenes.titlescene.support=Apoie o jogo
scenes.titlescene.update=Atualização
scenes.welcomescene.changelist=Lista de alterações
scenes.welcomescene.continue=Continuar
scenes.welcomescene.controller_body=Joga com um comando? Usa o analógico direito para controlar o cursor no ecrã. Prima RT/R2 ou o analógico direito para selecionar com o cursor.
scenes.welcomescene.controller_okay=Ok
scenes.welcomescene.controller_title=Entrada do controlador
scenes.welcomescene.lang_warning_msg=Alguns dos novos conteúdos desta atualização ainda não foram traduzidos. Algumas frases podem estar escritas em inglês. As equipas de tradução estão a trabalhar para resolver isto e uma tradução completa deverá ser lançada em breve. Agradecemos a sua paciência.
scenes.welcomescene.lang_warning_title=Tradução incompleta
scenes.welcomescene.patch_balance=Esta atualização contém ajustes no equilíbrio do jogo.
scenes.welcomescene.patch_bugfixes=Esta atualização contém correções de erros.
scenes.welcomescene.patch_msg=Esta atualização contém também alguns pequenos ajustes e melhorias de desempenho.
scenes.welcomescene.patch_translations=Esta atualização contém traduções adicionais.
scenes.welcomescene.update_msg=A versão 3.3 inclui uma área de testes para a próxima reformulação da missão na cidade, novos itens e uma série de pequenos ajustes e melhorias.
